Repository element-hq/element-android, pull requests merged in 2021-10, with the labels that each got.

#4083 Fix default encrypted for restricted
  changelog.d/4045.bugfix
  vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomController.kt
  vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomFragment.kt
  vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt
  vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewState.kt
Labels: A-Spaces, NextRelease

#4116 App doesn't take you to a Space after choosing to Join it
  changelog.d/3933.bugfix
  vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailActivity.kt
  vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheet.kt
  vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt
  vector/src/main/java/im/vector/app/features/spaces/SpaceExploreActivity.kt
  vector/src/main/java/im/vector/app/features/usercode/UserCodeActivity.kt
Labels: A-Spaces, NextRelease

#4124 Change call to action in filter room when space selected
  changelog.d/3048.bugfix
  vector/src/main/java/im/vector/app/features/home/room/filtered/FilteredRoomFooterItem.kt
  vector/src/main/java/im/vector/app/features/home/room/list/RoomListFooterController.kt
  vector/src/main/res/layout/item_room_filter_footer.xml
Labels: NextRelease

#2241 Add commands from element web
  vector/src/main/java/im/vector/app/features/command/Command.kt
  vector/src/main/java/im/vector/app/features/command/CommandParser.kt
  vector/src/main/java/im/vector/app/features/command/ParsedCommand.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewEvents.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
  vector/src/main/res/values/strings.xml
Labels: feature:slash_commands
