Repository element-hq/element-android, pull requests merged in 2021-12, with the labels that each got.

#4608 Fixed voice messages on Android 28 and below
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/VoiceMessageHelper.kt
Labels: X-Release-Blocker

#4607 Add robustness when getting data from cursors.
  changelog.d/4605.bugfix
  multipicker/src/main/java/im/vector/lib/multipicker/ContactPicker.kt
  multipicker/src/main/java/im/vector/lib/multipicker/FilePicker.kt
  multipicker/src/main/java/im/vector/lib/multipicker/utils/ContentResolverUtil.kt
  vector/src/main/java/im/vector/app/core/contacts/ContactsDataSource.kt
  vector/src/main/java/im/vector/app/core/intent/Filename.kt
Labels: X-Release-Blocker

#4663 Issue workflow updates for Delight
  .github/workflows/triage-move-labelled.yml
Labels: T-Task

#4667 Add automation to move messages bubbles issues to the message bubbles board
  .github/workflows/triage-move-labelled.yml
  changelog.d/4666.misc
Labels: A-Developer-Experience, T-Task

#4672 Fix graphql warning in issue automation workflow
  .github/workflows/triage-move-labelled.yml
  changelog.d/4671.misc
Labels: A-Developer-Experience, T-Task

#4708 Disable automatic opt-in screen display
  changelog.d/4559.feature
  vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
Labels: X-Release-Blocker

#2614 [issue-2610] implement setting to override nick color
  CHANGES.md
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/accountdata/UserAccountDataTypes.kt
  vector/src/main/java/im/vector/app/AppStateHandler.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/MatrixItemColorProvider.kt
  vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileController.kt
  vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileFragment.kt
  vector/src/main/res/values/strings.xml
Labels: X-Needs-Design, Z-Community-PR, X-Needs-Product

#2133 Maths support (MSC2191)
  changelog.d/2133.feature
  dependencies.gradle
  matrix-sdk-android/src/main/java/org/commonmark/ext/maths/DisplayMaths.kt
  matrix-sdk-android/src/main/java/org/commonmark/ext/maths/InlineMaths.kt
  matrix-sdk-android/src/main/java/org/commonmark/ext/maths/MathsExtension.kt
  matrix-sdk-android/src/main/java/org/commonmark/ext/maths/internal/DollarMathsDelimiterProcessor.kt
  matrix-sdk-android/src/main/java/org/commonmark/ext/maths/internal/MathsHtmlNodeRenderer.kt
  matrix-sdk-android/src/main/java/org/commonmark/ext/maths/internal/MathsNodeRenderer.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomModule.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/MarkdownParser.kt
  vector/build.gradle
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt
  vector/src/main/java/im/vector/app/features/html/EventHtmlRenderer.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/res/values/strings.xml
  vector/src/main/res/xml/vector_settings_labs.xml
Labels: Z-Community-PR, A-Timeline
