Repository element-hq/element-android, pull requests merged in 2022-10, with the labels that each got.

#6703 warn on cross signing reset
  changelog.d/6702.bugfix
  dependencies.gradle
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CryptoTestHelper.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/crosssigning/XSigningTest.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/crosssigning/MXCrossSigningInfo.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/model/UserVerificationLevel.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/DefaultCrossSigningService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/UpdateTrustWorker.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStoreMigration.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/migration/MigrateCryptoTo019.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/model/CrossSigningInfoEntity.kt
  vector/build.gradle
  vector/src/main/java/im/vector/app/core/epoxy/profiles/BaseProfileMatrixItem.kt
  vector/src/main/java/im/vector/app/core/ui/views/ShieldImageView.kt
  vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileFragment.kt
  vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListController.kt
  vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListViewModel.kt
  vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListViewState.kt
  vector/src/main/java/im/vector/app/features/spaces/people/SpacePeopleListController.kt
  vector/src/test/java/im/vector/app/features/MemberListViewModelTest.kt
  vector/src/test/java/im/vector/app/features/RoomMemberListControllerTest.kt
Labels: Z-NextRelease

#7278 fixing bug when room list is not updated being on background
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt
Labels: Z-NextRelease

#5716 Styling tweaks
  changelog.d/5712.misc
  library/ui-styles/src/main/res/values/dimens.xml
Labels: Z-Community-PR

#7184 [Bugfix] Fix crash on previewing image to upload on Android P
  changelog.d/7184.bugfix
  library/multipicker/src/main/java/im/vector/lib/multipicker/utils/ImageUtils.kt
Labels: Z-Community-PR

#6762 replace android:gravity for backward compatibility
  vector/src/main/res/drawable/poll_option_checked.xml
Labels: Z-Community-PR

#6757 [Bugfix #5029] disable emoji keyboard not applies to reply
  changelog.d/5029.bugfix
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerView.kt
  vector/src/main/res/layout/composer_layout.xml
  vector/src/main/res/layout/composer_layout_constraint_set_compact.xml
  vector/src/main/res/layout/composer_layout_constraint_set_expanded.xml
Labels: Z-Community-PR

#6215 Fix animated images only autoplaying sometimes
  changelog.d/6215.bugfix
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
  vector/src/main/java/im/vector/app/features/media/ImageContentRenderer.kt
Labels: Z-Community-PR

#5877 Support inline images in the timeline
  changelog.d/351.feature
  dependencies.gradle
  vector/build.gradle
  vector/src/main/java/im/vector/app/features/html/EventHtmlRenderer.kt
Labels: Z-Community-PR

#6633 Add privacy setting to disable personalized learning by the keyboard
  changelog.d/6633.feature
  library/ui-strings/src/main/res/values/strings.xml
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/ComposerEditText.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsSecurityPrivacyFragment.kt
  vector/src/main/res/xml/vector_settings_security_privacy.xml
Labels: Z-Community-PR

#7141 Add initial Sentry setup for crashes and perf tracking
  changelog.d/7076.misc
  dependencies.gradle
  dependencies_groups.gradle
  tools/danger/dangerfile.js
  vector-config/src/main/java/im/vector/app/config/Analytics.kt
  vector-config/src/main/java/im/vector/app/config/Config.kt
  vector/build.gradle
  vector/src/main/AndroidManifest.xml
  vector/src/main/java/im/vector/app/core/di/ConfigurationModule.kt
  vector/src/main/java/im/vector/app/features/analytics/AnalyticsConfig.kt
  vector/src/main/java/im/vector/app/features/analytics/impl/DefaultVectorAnalytics.kt
  vector/src/main/java/im/vector/app/features/analytics/impl/SentryFactory.kt
  vector/src/test/java/im/vector/app/features/analytics/impl/DefaultVectorAnalyticsTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeSentryFactory.kt
  vector/src/test/java/im/vector/app/test/fixtures/AnalyticsConfigFixture.kt
Labels: A-Analytics

#6726 Per room block unverified devices
  changelog.d/6725.bugfix
  library/ui-strings/src/main/res/values/strings.xml
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/E2eeConfigTest.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/CryptoService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/GlobalCryptoConfig.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DefaultCryptoService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/megolm/MXMegolmEncryption.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/IMXCryptoStore.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt
  vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileAction.kt
  vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileController.kt
  vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileFragment.kt
  vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileViewModel.kt
  vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileViewState.kt
  vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsViewState.kt
  vector/src/main/res/layout/item_form_switch.xml
Labels: Z-NextRelease

#7292 [Device Management] Show correct device type icons (PSG-775)
  changelog.d/7277.wip
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStoreMigration.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/mapper/MyDeviceLastSeenInfoEntityMapper.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/migration/MigrateCryptoTo019.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/migration/MigrateCryptoTo020.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/model/MyDeviceLastSeenInfoEntity.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/crypto/store/db/mapper/MyDeviceLastSeenInfoEntityMapperTest.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/VectorSettingsDevicesFragment.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/list/OtherSessionItem.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/list/OtherSessionsController.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/list/SessionInfoView.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/list/SetDeviceTypeIconUseCase.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewFragment.kt
  vector/src/test/java/im/vector/app/features/settings/devices/v2/list/SetDeviceTypeIconUseCaseTest.kt
Labels: Z-Merge After Release

#7285 Refactor: split TimelineFragment into MessageComposerFragment and VoiceRecorderFragment
  changelog.d/7285.misc
  vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewState.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerAction.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerView.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewEvents.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewState.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/voice/VoiceRecorderFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageItem.kt
  vector/src/main/res/layout/fragment_composer.xml
  vector/src/main/res/layout/fragment_timeline.xml
  vector/src/main/res/layout/fragment_voice_recorder.xml
Labels: A-Composer, A-Voice-Messages, A-Timeline, Z-Merge After Release

#7311 Fix breadcrumbs
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/voice/VoiceRecorderFragment.kt
Labels: Z-NextRelease

#7326 correct login_set_email_notice
  library/ui-strings/src/main/res/values/strings.xml
Labels: Z-Community-PR

#7340 [Device manager] Fixing navigation to session details + layout in session overview screen
  vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewFragment.kt
  vector/src/main/res/layout/fragment_session_overview.xml
Labels: Z-NextRelease, PR-Small

#7337 [Device management] Add lab flag for the feature (PSG-793)
  changelog.d/7336.feature
  library/ui-strings/src/main/res/values/strings.xml
  vector-app/src/debug/java/im/vector/app/features/debug/features/DebugFeaturesStateFactory.kt
  vector-app/src/debug/java/im/vector/app/features/debug/features/DebugVectorFeatures.kt
  vector-config/src/main/res/values/config-settings.xml
  vector/src/main/java/im/vector/app/features/VectorFeatures.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsSecurityPrivacyFragment.kt
  vector/src/main/res/xml/vector_settings_labs.xml
Labels: Z-NextRelease

#7325 [Device management] Hide the IP address and last activity date on current session (PSG-823)
  changelog.d/7324.wip
  vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewFragment.kt
Labels: Z-NextRelease, PR-Small

#7323 [Device management] Improve the parsing for OS of Desktop/Web sessions (PSG-823)
  changelog.d/7321.wip
  vector/src/main/java/im/vector/app/features/settings/devices/v2/ParseDeviceUserAgentUseCase.kt
  vector/src/test/java/im/vector/app/features/settings/devices/v2/ParseDeviceUserAgentUseCaseTest.kt
Labels: Z-NextRelease

#7352 [Device management] Add lab flag for matrix client info account data event (PSG-800)
  changelog.d/7344.feature
  library/ui-strings/src/main/res/values/strings.xml
  vector-config/src/main/res/values/config-settings.xml
  vector/src/main/java/im/vector/app/core/di/MavericksViewModelModule.kt
  vector/src/main/java/im/vector/app/core/session/ConfigureAndStartSessionUseCase.kt
  vector/src/main/java/im/vector/app/core/session/clientinfo/DeleteMatrixClientInfoUseCase.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/java/im/vector/app/features/settings/labs/VectorSettingsLabsAction.kt
  vector/src/main/java/im/vector/app/features/settings/labs/VectorSettingsLabsFragment.kt
  vector/src/main/java/im/vector/app/features/settings/labs/VectorSettingsLabsViewModel.kt
  vector/src/main/java/im/vector/app/features/settings/labs/VectorSettingsLabsViewState.kt
  vector/src/main/res/xml/vector_settings_labs.xml
  vector/src/main/res/xml/vector_settings_root.xml
  vector/src/test/java/im/vector/app/core/session/ConfigureAndStartSessionUseCaseTest.kt
  vector/src/test/java/im/vector/app/core/session/clientinfo/DeleteMatrixClientInfoUseCaseTest.kt
  vector/src/test/java/im/vector/app/features/settings/labs/VectorSettingsLabsViewModelTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeVectorPreferences.kt
Labels: Z-NextRelease

#7361 [Device management] Update the unknown verification status icon (PSG-824)
  changelog.d/7327.wip
  library/ui-strings/src/main/res/values/strings.xml
  library/ui-styles/src/main/res/values/colors.xml
  vector/build.gradle
  vector/src/main/java/im/vector/app/core/ui/views/ShieldImageView.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/GetDeviceFullInfoListUseCase.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/VectorSettingsDevicesFragment.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/filter/FilterDevicesUseCase.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/list/OtherSessionsController.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/list/SessionInfoView.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewFragment.kt
  vector/src/main/res/drawable/ic_shield_unknown.xml
  vector/src/main/res/drawable/ic_shield_unknown_no_border.xml
  vector/src/test/java/im/vector/app/features/settings/devices/v2/GetDeviceFullInfoListUseCaseTest.kt
  vector/src/test/java/im/vector/app/features/settings/devices/v2/filter/FilterDevicesUseCaseTest.kt
Labels: Z-NextRelease

#7360 Fix editing formatted messages in plain text editor
  changelog.d/7359.bugfix
  changelog.d/7359.sdk
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
Labels: Z-NextRelease

#7370 Device Manager Notification and Pusher Fixes
  vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewFragment.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewViewModel.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewViewState.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/TogglePushNotificationUseCase.kt
  vector/src/test/java/im/vector/app/core/pushers/PushersManagerTest.kt
  vector/src/test/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewViewModelTest.kt
  vector/src/test/java/im/vector/app/features/settings/devices/v2/overview/TogglePushNotificationUseCaseTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakePushersService.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeSessionAccountDataService.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeTogglePushNotificationUseCase.kt
Labels: Z-NextRelease

#7375 [Device Management] Redirect to the new screen everywhere when lab flag is on
  changelog.d/7374.feature
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsActivity.kt
Labels: Z-NextRelease, PR-Small

#7384 Bump WYSIWYG lib to 0.2.1
  changelog.d/7384.misc
  dependencies.gradle
Labels: Z-NextRelease

#7387 Voice Broadcast - Listening
  changelog.d/7387.wip
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageAudioEvent.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimelineService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineEventDataSource.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/VoiceBroadcastItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineEventsGroups.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageVoiceBroadcastItem.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastExtensions.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastHelper.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastPlayer.kt
Labels: Z-NextRelease

#7393 Add voice broadcast labs setting
  changelog.d/7393.wip
  library/ui-strings/src/main/res/values/strings.xml
  vector-config/src/main/res/values/config-settings.xml
  vector/src/main/java/im/vector/app/features/VectorFeatures.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/java/im/vector/app/features/settings/labs/VectorSettingsLabsFragment.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastConstants.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastRecorder.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastRecorderQ.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/usecase/StartVoiceBroadcastUseCase.kt
  vector/src/main/res/xml/vector_settings_labs.xml
Labels: Z-NextRelease

#7372 Handle properly when getUser returns null - prefer using getUserOrDefault
  changelog.d/7372.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/profile/GetProfileInfoTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/UpdateUserWorker.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/user/UserDataSource.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/widgets/helper/WidgetFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/LocationPinProvider.kt
  vector/src/main/java/im/vector/app/features/html/PillsPostProcessor.kt
  vector/src/main/java/im/vector/app/features/location/LocationSharingViewModel.kt
  vector/src/main/java/im/vector/app/features/location/live/map/UserLiveLocationViewStateMapper.kt
  vector/src/main/java/im/vector/app/features/notifications/NotifiableEventResolver.kt
  vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt
  vector/src/main/java/im/vector/app/features/roommemberprofile/devices/DeviceListBottomSheetViewModel.kt
  vector/src/main/java/im/vector/app/features/signout/soft/SoftLogoutViewModel.kt
  vector/src/main/java/im/vector/app/features/spaces/invite/SpaceInviteBottomSheetViewModel.kt
  vector/src/main/java/im/vector/app/features/usercode/UserCodeSharedViewModel.kt
Labels: Z-NextRelease

#7449 Voice Broadcast - Do not display the recording tile on the other sessions
  changelog.d/7431.bugfix
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/VoiceBroadcastItemFactory.kt
Labels: PR-Small

#7437 Fix new line and enter key presses deleting existing text in some keyboards
  changelog.d/7357.bugfix
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt
Labels: Z-NextRelease
