Repository element-hq/element-android, pull requests merged in 2022-04, with the labels that each got.

#5649 Replace "open settings" button by "disable" action in RageShake dialog if there is no session
  changelog.d/4445.bugfix
  vector/src/main/java/im/vector/app/features/rageshake/RageShake.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/res/values/strings.xml
Labels: PR-Small

#5614 Feature/aris/threads UI enhancements
  library/ui-styles/src/main/res/values/dimens.xml
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/threads/list/model/ThreadListItem.kt
  vector/src/main/java/im/vector/app/features/home/room/threads/list/views/ThreadListBottomSheet.kt
  vector/src/main/java/im/vector/app/features/home/room/threads/list/views/ThreadListFragment.kt
  vector/src/main/res/layout/bottom_sheet_thread_list.xml
  vector/src/main/res/layout/item_thread.xml
  vector/src/main/res/layout/item_timeline_event_base.xml
  vector/src/main/res/layout/view_room_detail_thread_toolbar.xml
  vector/src/main/res/layout/view_thread_notification_badge.xml
  vector/src/main/res/layout/view_thread_room_summary.xml
  vector/src/main/res/menu/menu_timeline.xml
  vector/src/main/res/values/strings.xml
Labels: Z-NextRelease

#5647 Feature/aris/threads beta feedback
  changelog.d/5647.feature
  library/ui-styles/src/main/res/drawable/bg_shadow_divider.xml
  vector-config/src/main/res/values/config-features.xml
  vector/src/main/java/im/vector/app/features/home/room/threads/list/views/ThreadListFragment.kt
  vector/src/main/java/im/vector/app/features/rageshake/BugReportActivity.kt
  vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt
  vector/src/main/java/im/vector/app/features/rageshake/ReportType.kt
  vector/src/main/res/layout/fragment_thread_list.xml
  vector/src/main/res/values/strings.xml
Labels: Z-NextRelease

#5692 Threads Beta opt-in mechanism
  changelog.d/5692.misc
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/SendingEventsDataSource.kt
  vector-config/src/main/res/values/urls.xml
  vector/src/main/java/im/vector/app/core/epoxy/bottomsheet/BottomSheetActionItem.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsEpoxyController.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/threads/ThreadsManager.kt
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsLabsFragment.kt
  vector/src/main/res/layout/item_bottom_sheet_action.xml
  vector/src/main/res/values/strings.xml
Labels: Z-NextRelease

#5659 Fix endless loading timeline if opened at non-existing event
  changelog.d/5659.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt
Labels: Z-Community-PR

#5481 Fix updating unread marker if not to latest chunk
  changelog.d/5481.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/ChunkEntityHelper.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt
Labels: Z-Community-PR

#5720 don't leave DMs when leaving all rooms in space
  changelog.d/5609.bugfix
  vector/src/main/java/im/vector/app/features/spaces/SpaceMenuViewModel.kt
Labels: T-Defect, A-Spaces, S-Critical

#5475 Fix some cases where the read marker line would not show up when it should
  changelog.d/5475.bugfix
  vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewState.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
Labels: Z-Community-PR

#5734 Updating posthog dev environment credentials
  changelog.d/5732.misc
  vector/src/debug/java/im/vector/app/config/AnalyticsConfig.kt
Labels: A-Analytics, PR-Small

#5554 Fix endless loading timeline due to conflicting chunks
  changelog.d/5554.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ChunkEntityQueries.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TokenChunkEventPersistor.kt
Labels: Z-Community-PR

#5731 Don't wrongly show non-space invites in the space panel
  changelog.d/5731.bugfix
  vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt
Labels: T-Defect

#5754 Fixing missing :vector test coverage in Jacoco report
  coverage.gradle
Labels: PR-Small

#5752 Disable live location sharing feature by default in debug config
  vector/build.gradle
  vector/src/main/java/im/vector/app/features/VectorFeatures.kt
Labels: PR-Small

#5757 Fix sorting of uploads in encrypted rooms
  changelog.d/5757.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/uploads/GetUploadsTask.kt
Labels: Z-Community-PR

#5763 FTUE - Server selection errors
  changelog.d/5749.wip
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/Extensions.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedServerSelectionFragment.kt
  vector/src/main/res/layout/fragment_ftue_server_selection_combined.xml
  vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeRegisterActionHandler.kt
Labels: Z-FTUE

#5727 Adds editorconfig for current code style
  .editorconfig
  build.gradle
  changelog.d/5727.misc
Labels: PR-Small

#5792 Replaces monarchy.doWithRealm with monarchy.awaitTransaction
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/SyncResponsePostTreatmentAggregatorHandler.kt
Labels: Z-NextRelease, PR-Small

#5652 Potentially fixes intermittent crashing from sending gallery images
  changelog.d/5652.bugfix
  library/multipicker/src/main/java/im/vector/lib/multipicker/CameraPicker.kt
  library/multipicker/src/main/java/im/vector/lib/multipicker/CameraVideoPicker.kt
  library/multipicker/src/main/java/im/vector/lib/multipicker/utils/MediaFileUtils.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/TemporaryFileCreator.kt
Labels: PR-Small

#5814 [Live location sharing] - Removing BeaconInfo structure
  changelog.d/5814.feature
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/livelocation/BeaconInfo.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/livelocation/LiveLocationBeaconContent.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/livelocation/DefaultLiveLocationAggregationProcessor.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/state/DefaultStateService.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/LiveLocationMessageItemFactory.kt
  vector/src/main/java/im/vector/app/features/location/LocationSharingService.kt
Labels: A-Location

#5826 Adds Suggested Tag in Explore Space
  changelog.d/5826.bugfix
  vector/src/main/java/im/vector/app/features/home/room/list/SpaceChildInfoItem.kt
  vector/src/main/java/im/vector/app/features/spaces/explore/SpaceDirectoryController.kt
  vector/src/main/res/layout/item_explore_space_child.xml
Labels: X-Needs-Design, PR-Small
