Repository element-hq/element-android, pull requests merged in 2022-09, with the labels that each got.

#6981 Allowing optional email registration
  changelog.d/6969.bugfix
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthEmailEntryFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt
  vector/src/main/res/layout/fragment_ftue_email_input.xml
Labels: Z-FTUE, PR-Small

#6988 space switcher empty spaces
  changelog.d/6754.bugfix
  library/ui-strings/src/main/res/values/strings.xml
  vector/src/main/java/im/vector/app/features/spaces/SpaceListFragment.kt
  vector/src/main/res/layout/fragment_space_list.xml
Labels: Z-NextRelease

#7009 Catch race condition while recording voice audio
  changelog.d/6989.bugfix
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/AudioMessageHelper.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
Labels: A-Voice-Messages

#7014 Feature/bma/fix fdroid crash
  vector-app/build.gradle
  vector-app/src/gplay/AndroidManifest.xml
  vector-app/src/main/AndroidManifest.xml
  vector/build.gradle
Labels: Z-NextRelease

#7013 New Layout - Fixes sync state not being visible
  vector/src/main/res/layout/fragment_new_home_detail.xml
Labels: PR-Small

#7012 Use libopus encoder for devices that lack the official codec
  changelog.d/7010.feature
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/AudioMessageHelper.kt
  vector/src/main/java/im/vector/app/features/voice/VoiceRecorderProvider.kt
Labels: A-Voice-Messages

#7018 App Layout - Fixes avatar not showing on fresh login
  vector/src/main/java/im/vector/app/features/home/NewHomeDetailFragment.kt
Labels: PR-Small

#7016 New Layout Accessibility Fixes
  changelog.d/7016.wip
  library/ui-strings/src/main/res/values/strings.xml
  vector/src/main/java/im/vector/app/features/spaces/NewSpaceSummaryItem.kt
  vector/src/main/java/im/vector/app/features/spaces/NewSubSpaceSummaryItem.kt
  vector/src/main/res/layout/fragment_new_home_detail.xml
  vector/src/main/res/layout/item_recent_room.xml
Labels: PR-Small

#7015 New Layout - Fixes recents background color not matching app bar
  vector/src/main/java/im/vector/app/features/home/room/list/home/recent/RecentRoomCarouselController.kt
  vector/src/main/res/layout/item_invites_count.xml
  vector/src/main/res/layout/item_recent_room.xml
Labels: PR-Small

#6998 Remove threads board automation
  .github/workflows/triage-labelled.yml
Labels: T-Task

#7003 applayout release experience
  library/ui-strings/src/main/res/values/strings.xml
  library/ui-styles/src/main/res/values-h720dp/dimens.xml
  library/ui-styles/src/main/res/values/dimens.xml
  vector/src/main/AndroidManifest.xml
  vector/src/main/java/im/vector/app/core/di/MavericksViewModelModule.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivityViewEvents.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/release/ReleaseCarouselData.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/release/ReleaseCarouselItem.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/release/ReleaseNotesAction.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/release/ReleaseNotesActivity.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/release/ReleaseNotesCarouselController.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/release/ReleaseNotesFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/release/ReleaseNotesPreferencesStore.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/release/ReleaseNotesViewEvents.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/release/ReleaseNotesViewModel.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
  vector/src/main/java/im/vector/app/features/popup/PopupAlertManager.kt
  vector/src/main/res/drawable-hdpi/ill_app_layout_onboarding_rooms.webp
  vector/src/main/res/drawable-hdpi/ill_app_layout_onboarding_spaces.webp
  vector/src/main/res/drawable-mdpi/ill_app_layout_onboarding_rooms.webp
  vector/src/main/res/drawable-mdpi/ill_app_layout_onboarding_spaces.webp
  vector/src/main/res/drawable-xhdpi/ill_app_layout_onboarding_rooms.webp
  vector/src/main/res/drawable-xhdpi/ill_app_layout_onboarding_spaces.webp
  vector/src/main/res/drawable-xxhdpi/ill_app_layout_onboarding_rooms.webp
  vector/src/main/res/drawable-xxhdpi/ill_app_layout_onboarding_spaces.webp
  vector/src/main/res/drawable-xxxhdpi/ill_app_layout_onboarding_rooms.webp
  vector/src/main/res/drawable-xxxhdpi/ill_app_layout_onboarding_spaces.webp
  vector/src/main/res/layout/activity_home.xml
  vector/src/main/res/layout/bottom_sheet_release_notes.xml
  vector/src/main/res/layout/item_release_carousel.xml
  vector/src/main/res/res/drawable-hdpi/app_layout_onboarding_feedback.webp
  vector/src/main/res/res/drawable-hdpi/app_layout_onboarding_spaces.webp
  vector/src/main/res/res/drawable-hdpi/app_layout_onboarding_welcome.webp
  vector/src/main/res/res/drawable-mdpi/app_layout_onboarding_feedback.webp
  vector/src/main/res/res/drawable-mdpi/app_layout_onboarding_spaces.webp
  vector/src/main/res/res/drawable-mdpi/app_layout_onboarding_welcome.webp
  vector/src/main/res/res/drawable-xhdpi/app_layout_onboarding_feedback.webp
  vector/src/main/res/res/drawable-xhdpi/app_layout_onboarding_spaces.webp
  vector/src/main/res/res/drawable-xhdpi/app_layout_onboarding_welcome.webp
  vector/src/main/res/res/drawable-xxhdpi/app_layout_onboarding_feedback.webp
  vector/src/main/res/res/drawable-xxhdpi/app_layout_onboarding_spaces.webp
  vector/src/main/res/res/drawable-xxhdpi/app_layout_onboarding_welcome.webp
  vector/src/main/res/res/drawable-xxxhdpi/app_layout_onboarding_feedback.webp
  vector/src/main/res/res/drawable-xxxhdpi/app_layout_onboarding_spaces.webp
  vector/src/main/res/res/drawable-xxxhdpi/app_layout_onboarding_welcome.webp
  vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
Labels: Z-NextRelease

#7021 obsolete settings are hidden when app layout flag is enabled
  changelog.d/6646.misc
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsLabsFragment.kt
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsPreferencesFragment.kt
  vector/src/main/res/xml/vector_settings_preferences.xml
Labels: Z-NextRelease

#6986 empty state for new invites screen
  changelog.d/6876.feature
  library/ui-strings/src/main/res/values/strings.xml
  vector/src/main/java/im/vector/app/features/home/room/list/home/invites/InvitesFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/invites/InvitesViewEvents.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/invites/InvitesViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/invites/InvitesViewState.kt
  vector/src/main/res/drawable/ic_invites_empty.xml
  vector/src/main/res/layout/fragment_invites.xml
Labels: Z-NextRelease

#7022 hide favourites and dms filters for a selected space, if they are empty
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt
Labels: Z-NextRelease

#7040 New Layout - Adds missing space list header
  changelog.d/7040.wip
  library/ui-strings/src/main/res/values/strings.xml
  vector/src/main/java/im/vector/app/features/spaces/NewSpaceListHeaderItem.kt
  vector/src/main/java/im/vector/app/features/spaces/NewSpaceSummaryController.kt
  vector/src/main/res/layout/item_new_space_list_header.xml
Labels: PR-Small

#7024 New Layout - Fixes padding of recents item selectable background
  vector/src/main/java/im/vector/app/features/home/room/list/home/recent/RecentRoomCarouselController.kt
  vector/src/main/res/layout/item_recent_room.xml
Labels: PR-Small

#7054 Fix invite to room in space
  changelog.d/7054.bugfix
  vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
  vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt
  vector/src/main/java/im/vector/app/features/home/NewHomeDetailFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
  vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt
  vector/src/main/java/im/vector/app/features/navigation/Navigator.kt
  vector/src/main/java/im/vector/app/features/permalink/PermalinkHandler.kt
  vector/src/main/java/im/vector/app/features/roomdirectory/PublicRoomsFragment.kt
  vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListFragment.kt
  vector/src/main/java/im/vector/app/features/settings/devices/VectorSettingsDevicesFragment.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/VectorSettingsDevicesFragment.kt
Labels: Z-NextRelease

#7020 fixed allscreens sanity test for enabled app layout flag
  vector-app/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt
  vector-app/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt
  vector-app/src/androidTest/java/im/vector/app/ui/robot/NewRoomRobot.kt
  vector-app/src/androidTest/java/im/vector/app/ui/robot/OnboardingRobot.kt
  vector-app/src/androidTest/java/im/vector/app/ui/robot/RoomListRobot.kt
  vector-app/src/androidTest/java/im/vector/app/ui/robot/space/SpaceCreateRobot.kt
  vector-app/src/androidTest/java/im/vector/app/ui/robot/space/SpaceRobot.kt
  vector/src/main/res/layout/fragment_space_list.xml
Labels: Z-NextRelease

#7000 Suggest @room when @channel, @everyone, or @here is typed in composer
  changelog.d/6529.feature
  vector/src/main/java/im/vector/app/features/autocomplete/member/AutocompleteMemberPresenter.kt
Labels: Z-Community-PR

#7038 New Layout - Labs Flag (to replace feature flag)
  changelog.d/7038.feature
  library/ui-strings/src/main/res/values/strings.xml
  vector-app/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt
  vector-app/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt
  vector-app/src/androidTest/java/im/vector/app/ui/robot/NewRoomRobot.kt
  vector-app/src/androidTest/java/im/vector/app/ui/robot/RoomListRobot.kt
  vector-app/src/androidTest/java/im/vector/app/ui/robot/settings/labs/LabFeaturesPreferences.kt
  vector-app/src/androidTest/java/im/vector/app/ui/robot/space/SpaceRobot.kt
  vector-config/src/main/res/values/config-settings.xml
  vector/src/debug/java/im/vector/app/features/debug/features/DebugFeaturesStateFactory.kt
  vector/src/debug/java/im/vector/app/features/debug/features/DebugVectorFeatures.kt
  vector/src/main/java/im/vector/app/core/platform/VectorBaseActivity.kt
  vector/src/main/java/im/vector/app/features/VectorFeatures.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsLabsFragment.kt
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsPreferencesFragment.kt
  vector/src/main/java/im/vector/app/features/spaces/SpaceListFragment.kt
  vector/src/main/res/xml/vector_settings_labs.xml
Labels: Z-NextRelease

#7085 Feature/bma/fix push
  changelog.d/6936.misc
  changelog.d/7068.bugfix
  vector-app/src/gplay/AndroidManifest.xml
  vector/build.gradle
  vector/src/fdroid/AndroidManifest.xml
  vector/src/fdroid/java/im/vector/app/fdroid/receiver/KeepInternalDistributor.kt
  vector/src/gplay/java/im/vector/app/push/fcm/VectorFirebaseMessagingService.kt
  vector/src/main/AndroidManifest.xml
  vector/src/main/java/im/vector/app/core/pushers/KeepInternalDistributor.kt
  vector/src/main/java/im/vector/app/core/pushers/PushParser.kt
  vector/src/main/java/im/vector/app/core/pushers/PushersManager.kt
  vector/src/main/java/im/vector/app/core/pushers/UnifiedPushHelper.kt
  vector/src/main/java/im/vector/app/core/pushers/UnifiedPushStore.kt
  vector/src/main/java/im/vector/app/core/pushers/VectorPushHandler.kt
  vector/src/main/java/im/vector/app/core/pushers/VectorUnifiedPushMessagingReceiver.kt
  vector/src/main/java/im/vector/app/core/pushers/model/PushDataFcm.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
  vector/src/main/java/im/vector/app/features/settings/notifications/VectorSettingsNotificationPreferenceFragment.kt
  vector/src/main/java/im/vector/app/features/settings/troubleshoot/TestEndpointAsTokenRegistration.kt
  vector/src/main/java/im/vector/app/features/settings/troubleshoot/TestUnifiedPushGateway.kt
  vector/src/test/java/im/vector/app/core/pushers/PushParserTest.kt
Labels: Z-NextRelease

#7124 room leaving prompt dialog now waits user to confirm
  changelog.d/7122.bugfix
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListFragment.kt
Labels: Z-NextRelease

#7140 Excluding legacy support library annotation usages
  changelog.d/7140.misc
  dependencies_groups.gradle
  library/jsonviewer/build.gradle
  vector/build.gradle
Labels: PR-Small

#7132 Adds dismissal to new chat bottom sheet actions
  changelog.d/7132.bugfix
  vector/src/main/java/im/vector/app/features/home/room/list/home/NewChatBottomSheet.kt
Labels: PR-Small

#7157 Fix build cache misses
  changelog.d/7157.misc
  library/ui-strings/build.gradle
Labels: PR-Small

#7130 Fix empty verification bottom sheet
  changelog.d/7130.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/SessionExtensions.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/user/UserService.kt
  vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomViewModel.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/IncomingVerificationRequestHandler.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/VerificationBottomSheet.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/VerificationBottomSheetViewModel.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/cancel/VerificationCancelController.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/choose/VerificationChooseMethodFragment.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/emoji/VerificationEmojiCodeController.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/emoji/VerificationEmojiCodeFragment.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/emoji/VerificationEmojiCodeViewModel.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/qrconfirmation/VerificationQrScannedByOtherController.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/request/VerificationRequestController.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/request/VerificationRequestFragment.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivityViewEvents.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
  vector/src/main/java/im/vector/app/features/home/UnknownDeviceDetectorSharedViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt
  vector/src/main/java/im/vector/app/features/popup/VerificationVectorAlert.kt
  vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt
Labels: Z-NextRelease

#7169 Fix regression on our dependency, due to merge of #6788.
  vector-app/build.gradle
Labels: Z-NextRelease

#7166 Enables New App Layout in Labs
  changelog.d/7166.misc
  vector-app/src/androidTest/java/im/vector/app/VerifySessionInteractiveTest.kt
  vector-app/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt
  vector-config/src/main/res/values/config-settings.xml
Labels: Z-NextRelease, PR-Small

#7177 add qr code option to home screen menu
  vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
  vector/src/main/res/menu/menu_new_home.xml
Labels: Z-NextRelease, Z-AppLayout

#7175 Show release experience screen on app update
  vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/release/ReleaseNotesPreferencesStore.kt
Labels: Z-NextRelease, PR-Small

#7154 Deferred DMs - Handle the local rooms within the new AppLayout
  changelog.d/7153.wip
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadReceiptEntityQueries.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/DefaultRoomService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/delete/DeleteLocalRoomTask.kt
  vector/src/main/java/im/vector/app/features/home/room/list/RoomListAction.kt
  vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewState.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListAction.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewState.kt
Labels: Z-NextRelease, PR-Small

#7186 Fixes Room List not getting updated when fragment is not in focus
  changelog.d/7186.bugfix
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeFilteredRoomsController.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewState.kt
Labels: Z-NextRelease

#7180 Deferred DMs - Add and enable the feature by default in the labs settings
  changelog.d/7180.feature
  library/ui-strings/src/main/res/values/strings.xml
  vector-app/src/debug/java/im/vector/app/features/debug/features/DebugFeaturesStateFactory.kt
  vector-app/src/debug/java/im/vector/app/features/debug/features/DebugVectorFeatures.kt
  vector-config/src/main/res/values/config-settings.xml
  vector/src/main/java/im/vector/app/features/VectorFeatures.kt
  vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomViewModel.kt
  vector/src/main/java/im/vector/app/features/createdirect/DirectRoomHelper.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/res/xml/vector_settings_labs.xml
Labels: Z-NextRelease

#7198 Allow configurable sync timeout
  changelog.d/7198.sdk
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CommonTestHelper.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/MatrixConfiguration.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/SyncConfig.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncThread.kt
  vector-app/src/androidTest/java/im/vector/app/core/utils/TestMatrixHelper.kt
Labels: matrix-sdk, PR-Small

#7159 Fix lint warning
  changelog.d/7159.misc
  library/ui-styles/src/debug/res/menu/menu_debug.xml
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/securestorage/SecretStoringUtils.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/util/BuildVersionSdkIntProvider.kt
  tools/lint/lint.xml
  vector-app/src/debug/java/im/vector/app/receivers/VectorDebugReceiver.kt
  vector-app/src/gplay/java/im/vector/app/push/fcm/GoogleFcmHelper.kt
  vector-app/src/main/java/im/vector/app/VectorApplication.kt
  vector/src/androidTest/java/im/vector/app/AndroidVersionTestOverrider.kt
  vector/src/androidTest/java/im/vector/app/TestBuildVersionSdkIntProvider.kt
  vector/src/androidTest/java/im/vector/app/features/pin/lockscreen/crypto/migrations/LegacyPinCodeMigratorTests.kt
  vector/src/androidTest/java/im/vector/app/features/voice/VoiceRecorderProviderTests.kt
  vector/src/main/java/im/vector/app/core/extensions/Context.kt
  vector/src/main/java/im/vector/app/core/platform/VectorBaseActivity.kt
  vector/src/main/java/im/vector/app/core/pushers/UnifiedPushStore.kt
  vector/src/main/java/im/vector/app/core/ui/views/KeysBackupBanner.kt
  vector/src/main/java/im/vector/app/core/utils/RingtoneUtils.kt
  vector/src/main/java/im/vector/app/features/call/conference/JitsiService.kt
  vector/src/main/java/im/vector/app/features/call/dialpad/CallDialPadBottomSheet.kt
  vector/src/main/java/im/vector/app/features/call/dialpad/PstnDialActivity.kt
  vector/src/main/java/im/vector/app/features/call/transfer/CallTransferActivity.kt
  vector/src/main/java/im/vector/app/features/call/transfer/CallTransferPagerAdapter.kt
  vector/src/main/java/im/vector/app/features/configuration/VectorConfiguration.kt
  vector/src/main/java/im/vector/app/features/crypto/keysbackup/restore/KeysBackupRestoreActivity.kt
  vector/src/main/java/im/vector/app/features/crypto/keysbackup/setup/KeysBackupSetupStep2Fragment.kt
  vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapEnterPassphraseFragment.kt
  vector/src/main/java/im/vector/app/features/disclaimer/DisclaimerDialog.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
  vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt
  vector/src/main/java/im/vector/app/features/home/NewHomeDetailFragment.kt
  vector/src/main/java/im/vector/app/features/home/ShortcutCreator.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/main/java/im/vector/app/features/homeserver/ServerUrlsRepository.kt
  vector/src/main/java/im/vector/app/features/lifecycle/VectorActivityLifecycleCallbacks.kt
  vector/src/main/java/im/vector/app/features/login/LoginCaptchaFragment.kt
  vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/CaptchaWebview.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/biometrics/BiometricHelper.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/KeyStoreCrypto.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/LockScreenKeysMigrator.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/migrations/MissingSystemKeyMigrator.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewModel.kt
  vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt
  vector/src/main/java/im/vector/app/features/rageshake/VectorUncaughtExceptionHandler.kt
  vector/src/main/java/im/vector/app/features/settings/VectorLocale.kt
  vector/src/main/java/im/vector/app/features/settings/VectorLocaleProvider.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsPreferencesFragment.kt
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsSecurityPrivacyFragment.kt
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsVoiceVideoFragment.kt
  vector/src/main/java/im/vector/app/features/settings/locale/LocalePickerController.kt
  vector/src/main/java/im/vector/app/features/settings/locale/LocalePickerViewModel.kt
  vector/src/main/java/im/vector/app/features/settings/locale/LocalePickerViewState.kt
  vector/src/main/java/im/vector/app/features/themes/ThemeUtils.kt
  vector/src/main/java/im/vector/app/features/voice/VoiceRecorderProvider.kt
  vector/src/main/java/im/vector/app/features/widgets/webview/WidgetWebView.kt
  vector/src/main/java/im/vector/app/features/workers/signout/ServerBackupStatusAction.kt
  vector/src/main/java/im/vector/app/features/workers/signout/ServerBackupStatusViewModel.kt
  vector/src/main/res/menu/menu_home.xml
  vector/src/main/res/menu/menu_manage_space.xml
Labels: Z-Merge After Release

#7210 Missing buildjet Emulator network
  .github/workflows/tests.yml
  vector-app/src/androidTest/java/im/vector/app/CantVerifyTest.kt
Labels: PR-Small

#7231 Add support for `/tableflip` command (#12)
  changelog.d/12.misc
  library/ui-strings/src/main/res/values/strings.xml
  vector/src/main/java/im/vector/app/features/command/Command.kt
  vector/src/main/java/im/vector/app/features/command/CommandParser.kt
  vector/src/main/java/im/vector/app/features/command/ParsedCommand.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
Labels: Z-Community-PR

#7129 Example screenshot test
  .github/workflows/tests.yml
  build.gradle
  vector/src/test/java/im/vector/app/screenshot/PaparazziExampleScreenshotTest.kt
  vector/src/test/snapshots/images/im.vector.app.screenshot_PaparazziExampleScreenshotTest_example paparazzi test.png
Labels: PR-Small

#7207 Instrumentation test coroutines
  changelog.d/7207.sdk
  matrix-sdk-android/build.gradle
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/account/ChangePasswordTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/account/DeactivateAccountTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CommonTestHelper.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CryptoTestData.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CryptoTestHelper.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/TestExtensions.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/DecryptRedactedEventTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/E2EShareKeysConfigTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/E2eeSanityTests.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/E2eeShareKeysHistoryTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/PreShareKeysTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/UnwedgingTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/crosssigning/XSigningTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/encryption/EncryptionTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/gossiping/KeyShareTests.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/gossiping/WithHeldTests.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/keysbackup/KeysBackupScenarioData.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/keysbackup/KeysBackupTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/keysbackup/KeysBackupTestHelper.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/replayattack/ReplayAttackTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/ssss/QuadSTests.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/verification/SASTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/verification/qrcode/VerificationTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/room/timeline/TimelineSimpleBackPaginationTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/search/SearchMessagesTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/space/SpaceCreationTest.kt
  matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/space/SpaceHierarchyTest.kt
Labels: PR-Large

#7223 Fix new layout flicker/leaks
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeFilteredRoomsController.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewState.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/header/RoomsHeadersData.kt
Labels: Z-NextRelease

#7246 [Crash] Autocomplete crashes on open
  gradle.properties
Labels: Z-NextRelease
