Repository element-hq/element-android, pull requests merged in 2022-03, with the labels that each got.

#5396 Fix Media cache size with negative values in the General Settings screen
  changelog.d/5394.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/file/FileService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultFileService.kt
  vector/src/main/java/im/vector/app/core/utils/FileUtils.kt
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt
Labels: Z-Community-PR

#5469 Fixing overlapping room image and title
  changelog.d/5468.bugfix
  vector/src/main/res/layout/view_room_detail_toolbar.xml
Labels: Z-NextRelease, PR-Small

#5472 Fix reactions summary crash
  changelog.d/5463.bugfix
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/CallItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/EncryptedItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/EncryptionItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/TimelineItemFactoryParams.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/VerificationItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/WidgetItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/MessageInformationDataFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/MessageItemAttributesFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/ReactionsSummaryFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsBaseMessageItem.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageItem.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/CallTileTimelineItem.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageInformationData.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/StatusTileTimelineItem.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/VerificationRequestItem.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/WidgetTileTimelineItem.kt
Labels: Z-NextRelease

#5384 Add padding before first own message
  changelog.d/5384.misc
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageItem.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/style/TimelineMessageLayout.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/style/TimelineMessageLayoutFactory.kt
  vector/src/main/res/layout/view_message_bubble.xml
Labels: Z-Community-PR

#5450 Fix missing messages when forward paging with chunks > 50 messages
  changelog.d/5448.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt
Labels: Z-Community-PR

#5181 #4533: improve headers UI in room/messages lists
  changelog.d/4533.misc
  dependencies.gradle
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/UpdatableLivePageResult.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/DefaultRoomService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryDataSource.kt
  vector/build.gradle
  vector/src/main/java/im/vector/app/features/home/room/list/RoomCategoryItem.kt
  vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/list/RoomListSectionBuilderGroup.kt
  vector/src/main/java/im/vector/app/features/home/room/list/RoomListSectionBuilderSpace.kt
  vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/list/RoomsSection.kt
  vector/src/main/java/im/vector/app/features/home/room/list/SectionHeaderAdapter.kt
  vector/src/main/java/im/vector/app/features/spaces/manage/AddRoomListController.kt
  vector/src/main/java/im/vector/app/features/spaces/manage/SpaceAddRoomFragment.kt
  vector/src/main/java/im/vector/app/features/spaces/manage/SpaceAddRoomsViewModel.kt
  vector/src/main/res/layout/item_room_category.xml
Labels: Z-WTF

#5558 Fixing crash when tapping timeline verification item
  changelog.d/5540.bugfix
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
Labels: Z-Crash, PR-Small

#5550 Presence indicator theme attribute
  changelog.d/5513.misc
  library/ui-styles/src/main/res/values/colors.xml
  library/ui-styles/src/main/res/values/palette_mobile.xml
  library/ui-styles/src/main/res/values/theme_dark.xml
  library/ui-styles/src/main/res/values/theme_light.xml
  vector/src/main/res/drawable/ic_presence_online.xml
Labels: PR-Small

#5572 Show stickers on click
  changelog.d/5572.misc
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
  vector/src/main/java/im/vector/app/features/media/RoomEventsAttachmentProvider.kt
Labels: Z-Community-PR, X-Needs-Product

#5551 Fix local echos not being shown when re-opening rooms
  changelog.d/5551.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/SendingEventsDataSource.kt
Labels: Z-Community-PR

#5576 Threads Migration
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/MatrixConfiguration.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/lightweight/LightweightSettingsStorage.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/di/WorkManagerProvider.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/threads/FetchThreadSummariesTask.kt
  vector-config/src/main/res/values/config-settings.xml
  vector/src/main/java/im/vector/app/core/di/SingletonModule.kt
  vector/src/main/java/im/vector/app/features/MainActivity.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivityViewEvents.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsLabsFragment.kt
  vector/src/main/res/values/strings.xml
  vector/src/main/res/xml/vector_settings_labs.xml
Labels: Z-NextRelease

#5517 FTUE - Single loading state
  changelog.d/5517.misc
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/Extensions.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewState.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/AbstractFtueAuthFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthLoginFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthResetPasswordFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthResetPasswordMailConfirmationFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt
  vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
Labels: Z-FTUE

#5645 Fix regression from #4471
  vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomActivity.kt
  vector/src/main/java/im/vector/app/features/discovery/DiscoverySettingsController.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/search/SearchFragment.kt
  vector/src/main/java/im/vector/app/features/login/LoginFragment.kt
  vector/src/main/java/im/vector/app/features/roomprofile/uploads/files/RoomUploadsFilesFragment.kt
  vector/src/main/java/im/vector/app/features/roomprofile/uploads/media/RoomUploadsMediaFragment.kt
  vector/src/main/java/im/vector/app/features/settings/devtools/AccountDataEpoxyController.kt
  vector/src/main/java/im/vector/app/features/settings/threepids/ThreePidsSettingsController.kt
Labels: Z-NextRelease

#5519 FTUE - Finalising personalisation journey
  changelog.d/5519.wip
  vector/src/androidTest/java/im/vector/app/ui/robot/OnboardingRobot.kt
  vector/src/main/res/values/donottranslate.xml
  vector/src/main/res/values/strings.xml
  vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeVectorFeatures.kt
Labels: Z-FTUE

#5663 Use truncate mode to replace the contents of existing files
  changelog.d/5663.bugfix
  vector/src/main/java/im/vector/app/core/extensions/Context.kt
  vector/src/main/java/im/vector/app/features/crypto/keys/KeysExporter.kt
  vector/src/main/java/im/vector/app/features/crypto/keysbackup/setup/KeysBackupSetupStep3Fragment.kt
  vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapSaveRecoveryKeyFragment.kt
  vector/src/main/java/im/vector/app/features/settings/devtools/KeyRequestsFragment.kt
  vector/src/test/java/im/vector/app/features/crypto/keys/KeysExporterTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeContext.kt
Labels: Z-Community-PR
