Repository element-hq/element-android, pull requests merged in 2022-08, with the labels that each got.

#6710 Fixing `IllegalStateException: You should authenticate before using this` when restoring app
  changelog.d/6709.bugfix
  vector/src/main/java/im/vector/app/core/di/ActiveSessionHolder.kt
  vector/src/main/java/im/vector/app/core/di/ActiveSessionSetter.kt
  vector/src/main/java/im/vector/app/core/di/SessionInitializer.kt
  vector/src/main/java/im/vector/app/core/pushers/VectorMessagingReceiver.kt
  vector/src/main/java/im/vector/app/features/start/StartAppViewModel.kt
Labels: Z-Crash, Z-NextRelease

#6692 No signoff, no changelog for dependabot's PR
  tools/danger/dangerfile.js
Labels: A-DevX

#6688 [Location sharing] Invisible text on map symbol
  changelog.d/6687.bugfix
  vector/src/main/java/im/vector/app/features/location/MapTilerMapView.kt
Labels: PR-Small

#6681 [FTUE] Memory leak on FtueAuthSplashCarouselFragment
  changelog.d/6680.misc
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthSplashCarouselFragment.kt
Labels: PR-Small

#6654 [Location share] Update minimum sending period to 5 seconds for a live
  changelog.d/6653.misc
  vector/src/main/java/im/vector/app/features/location/Config.kt
  vector/src/main/java/im/vector/app/features/location/LocationTracker.kt
  vector/src/test/java/im/vector/app/features/location/LocationTrackerTest.kt
Labels: PR-Small

#6728 Fixing CI crashing during compilation/linting
  .github/workflows/build.yml
  .github/workflows/nightly.yml
  .github/workflows/post-pr.yml
  .github/workflows/quality.yml
  .github/workflows/tests.yml
  docs/nightly_build.md
Labels: z-CI, PR-Small

#6679 [Timeline] Memory leak in audio message playback tracker
  changelog.d/6678.misc
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerAction.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
Labels: PR-Small

#6741 FTUE - Focus errors showing on wrong page
  changelog.d/6737.bugfix
  vector/src/main/java/im/vector/app/core/extensions/TextInputLayout.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedLoginFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedRegisterFragment.kt
  vector/src/main/res/layout/fragment_ftue_combined_login.xml
  vector/src/main/res/layout/fragment_ftue_combined_register.xml
Labels: Z-FTUE, PR-Small

#6748 Fixing flaky `CantVerifyTest`
  vector/build.gradle
  vector/src/androidTest/java/im/vector/app/CantVerifyTest.kt
  vector/src/androidTest/java/im/vector/app/ClearCurrentSessionRule.kt
  vector/src/main/java/im/vector/app/features/analytics/store/AnalyticsStore.kt
Labels: Z-Tests

#6736 Fixes crash when entering non ascii username during account creation
  changelog.d/6735.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/Extensions.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
  vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeRegistrationWizard.kt
Labels: Z-NextRelease, PR-Small

#6780 Avoid crashes from unknown exceptions on lockscreen key migration.
  changelog.d/6769.bugfix
  vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/LockScreenKeysMigrator.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/migrations/MissingSystemKeyMigrator.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/migrations/SystemKeyV1Migrator.kt
  vector/src/test/java/im/vector/app/features/pin/lockscreen/crypto/migrations/LockScreenKeysMigratorTests.kt
  vector/src/test/java/im/vector/app/features/pin/lockscreen/crypto/migrations/MissingSystemKeyMigratorTests.kt
  vector/src/test/java/im/vector/app/features/pin/lockscreen/crypto/migrations/SystemKeyV1MigratorTests.kt
Labels: A-Pin code, Z-NextRelease

#6784 Fix lockscreen's 'device locked' crash on Android 12 and 12L devices
  changelog.d/6768.bugfix
  vector/src/androidTest/java/im/vector/app/features/pin/lockscreen/biometrics/BiometricHelperTests.kt
  vector/src/androidTest/java/im/vector/app/features/pin/lockscreen/crypto/LockScreenKeyRepositoryTests.kt
  vector/src/main/java/im/vector/app/features/pin/PinFragment.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/biometrics/BiometricHelper.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/configuration/LockScreenConfiguration.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/configuration/LockScreenConfiguratorProvider.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/KeyStoreCrypto.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/di/LockScreenModule.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenAction.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenFragment.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewEvent.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewModel.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewState.kt
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsPinFragment.kt
  vector/src/test/java/im/vector/app/features/pin/lockscreen/fragment/LockScreenViewModelTests.kt
Labels: A-Pin code, Z-NextRelease

#6793 Disabling unsupported play store language
  tools/release/pushPlayStoreMetaData.sh
Labels: PR-Small

#6796 Improve tests for lockscreen
  vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewModel.kt
  vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewState.kt
  vector/src/test/java/im/vector/app/features/pin/lockscreen/fragment/LockScreenViewModelTests.kt
  vector/src/test/java/im/vector/app/test/Extensions.kt
  vector/src/test/java/im/vector/app/test/FlowTestObserver.kt
Labels: PR-Small

#6747 [Notification] - Handle creation of notification for live location and poll start (PSG-41)
  changelog.d/6746.feature
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageBeaconLocationDataContent.kt
  vector/src/main/java/im/vector/app/features/notifications/NotifiableEventResolver.kt
Labels: PR-Small

#6795 New App Layout: Space name reflected in toolbar
  changelog.d/6795.wip
  vector/src/main/java/im/vector/app/features/home/NewHomeDetailFragment.kt
  vector/src/main/res/layout/fragment_new_home_detail.xml
Labels: PR-Small

#6866 Start DM on first message when selecting "direct message" from the room member details screen
  changelog.d/5525.wip
  vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomViewModel.kt
  vector/src/main/java/im/vector/app/features/createdirect/DirectRoomHelper.kt
Labels: PR-Small

#6801 New App Layout: Adds New Chat Bottom Sheet
  changelog.d/6801.wip
  vector/src/main/java/im/vector/app/core/di/FragmentModule.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/NewChatBottomSheet.kt
  vector/src/main/res/drawable/ic_chat.xml
  vector/src/main/res/drawable/ic_room_add.xml
  vector/src/main/res/drawable/ic_room_explore.xml
  vector/src/main/res/layout/fragment_new_chat_bottom_sheet.xml
  vector/src/main/res/values/strings.xml
Labels: PR-Small

#6887 dialpad moved from bottom navigation tab to a separate activity
  changelog.d/6787.wip
  vector/src/main/AndroidManifest.xml
  vector/src/main/java/im/vector/app/features/call/dialpad/PstnDialActivity.kt
  vector/src/main/java/im/vector/app/features/home/NewHomeDetailFragment.kt
  vector/src/main/res/menu/room_list.xml
Labels: Team: Delight, Z-AppLayout

#6834 Allow empty SSO `identity_providers`
  changelog.d/6827.bugfix
  vector/src/main/java/im/vector/app/features/login/AbstractSSOLoginFragment.kt
  vector/src/main/java/im/vector/app/features/login/LoginFragment.kt
  vector/src/main/java/im/vector/app/features/login/LoginMode.kt
  vector/src/main/java/im/vector/app/features/login/LoginSignUpSignInSelectionFragment.kt
  vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt
  vector/src/main/java/im/vector/app/features/login/SocialLoginButtonsView.kt
  vector/src/main/java/im/vector/app/features/login/SsoState.kt
  vector/src/main/java/im/vector/app/features/onboarding/StartAuthenticationFlowUseCase.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/AbstractSSOFtueAuthFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedLoginFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedRegisterFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthLoginFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthSignUpSignInSelectionFragment.kt
  vector/src/main/java/im/vector/app/features/signout/soft/SoftLogoutFragment.kt
  vector/src/main/java/im/vector/app/features/signout/soft/SoftLogoutViewModel.kt
  vector/src/test/java/im/vector/app/features/onboarding/StartAuthenticationFlowUseCaseTest.kt
Labels: Z-FTUE, Z-NextRelease

#6884 Ensure sync thread is started
  changelog.d/6884.bugfix
  changelog.d/6884.sdk
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/debug/DebugService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/Session.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/sync/SyncService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmLiveEntityObserver.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/tools/RealmDebugTools.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/debug/DefaultDebugService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/di/MatrixModule.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultSession.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/EventSenderProcessorThread.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/DefaultSyncService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncThread.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/BackgroundDetectionObserver.kt
  vector/src/main/java/im/vector/app/VectorApplication.kt
  vector/src/main/java/im/vector/app/core/di/ActiveSessionHolder.kt
  vector/src/main/java/im/vector/app/core/extensions/Session.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineAsyncHelper.kt
  vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt
  vector/src/main/java/im/vector/app/features/rageshake/ProcessInfo.kt
Labels: Z-NextRelease

#6890 Missing push notifications on login
  changelog.d/6891.bugfix
  vector/src/main/java/im/vector/app/core/pushers/UnifiedPushHelper.kt
Labels: Z-NextRelease, PR-Small

#6873 FTUE - Fix trusting certificates during edit server flow
  changelog.d/6864.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/Extensions.kt
  vector/src/main/java/im/vector/app/features/login/HomeServerConnectionConfigFactory.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingAction.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewEvents.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/AbstractFtueAuthFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt
  vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeHomeServerConnectionConfigFactory.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeStartAuthenticationFlowUseCase.kt
  vector/src/test/java/im/vector/app/test/fixtures/FailureFixture.kt
Labels: Z-FTUE, Z-NextRelease

#6862 FTUE - Crash fixes
  changelog.d/6855.bugfix
  changelog.d/6860.bugfix
  changelog.d/6861.bugfix
  vector/src/main/java/im/vector/app/core/extensions/Throwable.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCaptchaFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt
  vector/src/main/res/layout/fragment_ftue_login_captcha.xml
  vector/src/main/res/layout/view_stub_webview.xml
  vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
Labels: Z-Crash, Z-FTUE, Z-NextRelease

#6868 Space Switching: Adds Toolbar Click To Open Space Settings
  changelog.d/6859.wip
  vector/src/main/java/im/vector/app/features/home/NewHomeDetailFragment.kt
Labels: PR-Small

#6888 FTUE - Allow changing server on onboarding start error
  changelog.d/6718.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/Extensions.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewEvents.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedServerSelectionFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt
  vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
Labels: Z-FTUE, Z-NextRelease

#6908 Fix crash when signing out.
  vector/src/main/java/im/vector/app/core/di/ActiveSessionHolder.kt
Labels: Z-NextRelease

#6127 Create the DM when sending an event
  changelog.d/5525.wip
  dependencies.gradle
  matrix-sdk-android/build.gradle
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/EventType.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/identity/ThreePid.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/create/CreateRoomParams.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/create/CreateRoomStateEvent.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/tasks/SendEventTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo036.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/LocalRoomSummaryEntity.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/SessionRealmModule.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/LocalRoomSummaryEntityQueries.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/di/MoshiProvider.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomModule.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateLocalRoomStateEventsTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateLocalRoomTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateRoomBody.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateRoomFromLocalRoomTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateRoomTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/LocalRoomThirdPartyInviteContent.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/delete/DeleteLocalRoomTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/threepid/ThreePidInviteBody.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/state/SendStateTask.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/create/DefaultCreateLocalRoomStateEventsTaskTest.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/create/DefaultCreateRoomFromLocalRoomTaskTest.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultGetActiveBeaconInfoForUserTaskTest.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeMonarchy.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeStateEventDataSource.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineEventVisibilityHelper.kt
Labels: PR-Large

#6927 FTUE: Make entering a custom Homeserver address faster by focusing the input
  changelog.d/6926.misc
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedServerSelectionFragment.kt
Labels: Z-Community-PR

#6941 Fixing /joinSpace and /addToSpace commands
  changelog.d/6844.bugfix
  vector/src/main/java/im/vector/app/features/command/CommandParser.kt
  vector/src/test/java/im/vector/app/features/command/CommandParserTest.kt
Labels: PR-Small

#6917 Feature/bma/incr sync perf
  changelog.d/6917.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/DefaultCrossSigningService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/UpdateTrustWorker.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/SessionComponent.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/RoomMemberEventHandler.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryUpdater.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponseHandler.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponsePostTreatmentAggregator.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/SyncResponsePostTreatmentAggregatorHandler.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/UpdateUserWorker.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/room/RoomSyncHandler.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/worker/MatrixWorkerFactory.kt
Labels: Z-NextRelease

#6980 Fix crash on PIN code settings screen
  changelog.d/6979.bugfix
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsPinFragment.kt
Labels: A-Pin code
