Repository element-hq/element-android, pull requests merged in 2022-12, with the labels that each got.

#7725 Do not propagate failure if saving the filter server side fails
  changelog.d/7725.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/filter/GetCurrentFilterTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/filter/SaveFilterTask.kt
Labels: Z-NextRelease

#7756 Update project board IDs for automation
  .github/workflows/triage-labelled.yml
  .github/workflows/triage-move-review-requests.yml
Labels: T-Task

#7771 thread message notification should navigate to thread timeline
  changelog.d/7770.bugfix
  vector/src/main/java/im/vector/app/features/home/room/threads/ThreadsActivity.kt
  vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt
  vector/src/main/java/im/vector/app/features/notifications/RoomGroupMessageCreator.kt
Labels: Z-NextRelease

#7775 threads are enabled by default end forced to enabled for existing users
  changelog.d/5503.misc
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/MatrixConfiguration.kt
  vector-config/src/main/res/values/config-settings.xml
  vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/java/im/vector/app/features/settings/labs/VectorSettingsLabsFragment.kt
Labels: Z-NextRelease

#7757 [Poll] Poll end event is not recognized (PSG-948 and PSG-949)
  changelog.d/7753.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/DefaultPollAggregationProcessor.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/DefaultPollAggregationProcessorTest.kt
Labels: PR-Small

#7776 changed copy for threads labs flag
  library/ui-strings/src/main/res/values/strings.xml
Labels: Z-NextRelease, PR-Small

#7766 thread list loading
  changelog.d/5819.misc
  matrix-sdk-android-flow/src/main/java/org/matrix/android/sdk/flow/FlowRoom.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/threads/FetchThreadsResult.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/threads/ThreadFilter.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/threads/ThreadLivePageResult.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/threads/ThreadsService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/ThreadSummaryHelper.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo046.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/SessionRealmModule.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/threads/ThreadListPageEntity.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/threads/ThreadSummaryEntity.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ThreadSummaryPageEntityQueries.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAPI.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/threads/FetchThreadSummariesTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/threads/ThreadSummariesResponse.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/threads/DefaultThreadsService.kt
  vector/src/main/java/im/vector/app/features/home/room/threads/list/viewmodel/ThreadListController.kt
  vector/src/main/java/im/vector/app/features/home/room/threads/list/viewmodel/ThreadListPagedController.kt
  vector/src/main/java/im/vector/app/features/home/room/threads/list/viewmodel/ThreadListViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/threads/list/viewmodel/ThreadListViewState.kt
  vector/src/main/java/im/vector/app/features/home/room/threads/list/views/ThreadListFragment.kt
Labels: Z-NextRelease

#7796 [Session manager] Security recommendations cards: whole view should be tappable (PSG-1117)
  changelog.d/7795.feature
  vector/src/main/java/im/vector/app/features/settings/devices/v2/list/SecurityRecommendationView.kt
  vector/src/main/res/layout/view_security_recommendation.xml
Labels: PR-Small

#7785 [Session manager] Other sessions list: filter option is displayed when selection mode is enabled (PSG-1113)
  changelog.d/7784.bugfix
  vector/src/main/java/im/vector/app/features/settings/devices/v2/othersessions/OtherSessionsFragment.kt
Labels: PR-Small

#7791 [Session manager] Other sessions: Filter bottom sheet cut in landscape mode (PSG-1107)
  changelog.d/7786.bugfix
  vector/src/main/res/layout/bottom_sheet_device_manager_filter.xml
Labels: PR-Small

#7793 [Session Manager] Other sessions list: cannot select/deselect session by a long press when in select mode (PSG-1111)
  changelog.d/7792.bugfix
  vector/src/main/java/im/vector/app/features/settings/devices/v2/othersessions/OtherSessionsFragment.kt
Labels: PR-Small

#7808 No typing for ignored user
  changelog.d/2965.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/room/RoomTypingUsersHandler.kt
Labels: PR-Small

#7821 Replace the player timeline
  changelog.d/7821.misc
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageVoiceBroadcastListeningItem.kt
  vector/src/main/res/layout/item_timeline_event_voice_broadcast_listening_stub.xml
Labels: T-Enhancement, A-Voice Broadcast
