Repository element-hq/element-android, pull requests merged in 2022-06, with the labels that each got.

#6042 FTUE - Sign up analytics
  changelog.d/5285.wip
  vector/src/main/java/im/vector/app/features/analytics/extensions/SignUpExt.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivityViewState.kt
  vector/src/main/java/im/vector/app/features/login/LoginActivity.kt
  vector/src/main/java/im/vector/app/features/login/LoginFragment.kt
  vector/src/main/java/im/vector/app/features/login/LoginSignUpSignInSelectionFragment.kt
  vector/src/main/java/im/vector/app/features/login/SocialLoginButtonsView.kt
  vector/src/main/java/im/vector/app/features/login2/LoginFragmentSignupUsername2.kt
  vector/src/main/java/im/vector/app/features/login2/LoginFragmentToAny2.kt
  vector/src/main/java/im/vector/app/features/onboarding/AuthenticationDescription.kt
  vector/src/main/java/im/vector/app/features/onboarding/Login2Variant.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewState.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/AbstractSSOFtueAuthFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedLoginFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedRegisterFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthLoginFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthSignUpSignInSelectionFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt
Labels: Z-FTUE

#6214 Homeserver version without patch number parsing
  changelog.d/6017.misc
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/extensions/Strings.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/version/HomeServerVersion.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/auth/version/HomeServerVersionTest.kt
Labels: matrix-sdk, PR-Small

#6293 FTUE - Minor tweaks
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthAccountCreatedFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthPersonalizationCompleteFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthUseCaseFragment.kt
  vector/src/main/res/layout/fragment_ftue_auth_use_case.xml
  vector/src/main/res/layout/fragment_ftue_personalization_complete.xml
Labels: Z-FTUE, PR-Small

#6223 Avoid manual line breaks in exit onboarding dialog copy
  changelog.d/6087.misc
  vector/src/main/res/values-bg/strings.xml
  vector/src/main/res/values-ca/strings.xml
  vector/src/main/res/values-cs/strings.xml
  vector/src/main/res/values-de/strings.xml
  vector/src/main/res/values-eo/strings.xml
  vector/src/main/res/values-es/strings.xml
  vector/src/main/res/values-et/strings.xml
  vector/src/main/res/values-eu/strings.xml
  vector/src/main/res/values-fi/strings.xml
  vector/src/main/res/values-fr-rCA/strings.xml
  vector/src/main/res/values-fr/strings.xml
  vector/src/main/res/values-hu/strings.xml
  vector/src/main/res/values-in/strings.xml
  vector/src/main/res/values-it/strings.xml
  vector/src/main/res/values-kab/strings.xml
  vector/src/main/res/values-lv/strings.xml
  vector/src/main/res/values-nb-rNO/strings.xml
  vector/src/main/res/values-nl/strings.xml
  vector/src/main/res/values-pl/strings.xml
  vector/src/main/res/values-pt-rBR/strings.xml
  vector/src/main/res/values-ru/strings.xml
  vector/src/main/res/values-sk/strings.xml
  vector/src/main/res/values-sq/strings.xml
  vector/src/main/res/values-sv/strings.xml
  vector/src/main/res/values-tr/strings.xml
  vector/src/main/res/values-uk/strings.xml
  vector/src/main/res/values-vi/strings.xml
  vector/src/main/res/values/strings.xml
Labels: Z-FTUE, Z-NextRelease, PR-Small, Z-Weblate

#6296 Allow sharing text mimetype content via android's share menu
  changelog.d/6285.feature
  vector/src/main/java/im/vector/app/features/attachments/AttachmentsHelper.kt
Labels: PR-Small

#6290 Fixes large images crashing when opened in timeline
  changelog.d/6290.bugfix
  vector/src/main/java/im/vector/app/features/media/ImageContentRenderer.kt
Labels: PR-Small

#6297 Making bug report screenshots opt in instead of opt out
  changelog.d/6261.misc
  vector/src/main/java/im/vector/app/features/rageshake/BugReportActivity.kt
  vector/src/main/res/layout/activity_bug_report.xml
Labels: PR-Small

#6154 Fixes /upgraderoom command not doing anything
  changelog.d/6154.bugfix
  vector/src/main/java/im/vector/app/core/utils/DataSource.kt
  vector/src/test/java/im/vector/app/core/utils/DataSourceTest.kt
Labels: PR-Small

#6304 [SDK] Improve location sharing service api (PSF-1004)
  changelog.d/5864.sdk
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/location/LocationSharingService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/send/SendService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/state/StateService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/LiveLocationShareAggregatedSummaryMapper.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomModule.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/location/DefaultLocationSharingService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/location/SendLiveLocationTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/location/SendStaticLocationTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/location/StartLiveLocationShareTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/location/StopLiveLocationShareTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/DefaultSendService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/state/DefaultStateService.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/pushers/DefaultAddPusherTaskTest.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultLocationSharingServiceTest.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultSendLiveLocationTaskTest.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultSendStaticLocationTaskTest.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultStartLiveLocationShareTaskTest.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultStopLiveLocationShareTaskTest.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeEventSenderProcessor.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeLocalEchoEventFactory.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeMonarchy.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeRealm.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeSendStateTask.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeStateEventDataSource.kt
  vector/src/main/java/im/vector/app/features/location/LocationSharingService.kt
  vector/src/main/java/im/vector/app/features/location/LocationSharingViewModel.kt
Labels: matrix-sdk, A-Location

#6307 Missing unit test coverage
  .github/workflows/tests.yml
  build.gradle
  coverage.gradle
  matrix-sdk-android/build.gradle
  vector/build.gradle
Labels: Z-Tests, Z-Sonar

#6362 Fixing concurrent `dispatchTo` crash
  changelog.d/5821.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/SessionListeners.kt
Labels: PR-Small

#6370 Fix CI lint tasks unexpectedly crashing
  .github/workflows/quality.yml
Labels: z-CI, PR-Small

#6357 Fix formatted_body being parsed as Markdown
  changelog.d/6357.bugfix
  vector/src/main/java/im/vector/app/features/html/EventHtmlRenderer.kt
Labels: Z-Community-PR

#6366 Poll view state unit tests [PSF-1130]
  changelog.d/6366.misc
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/PollCreationInfo.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/PollItemViewStateFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageInformationData.kt
  vector/src/main/java/im/vector/app/features/poll/PollViewState.kt
  vector/src/test/java/im/vector/app/features/home/room/detail/timeline/factory/PollItemViewStateFactoryTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeStringProvider.kt
Labels: A-Polls

#6328 Feature/bca/verif resist no age
  changelog.d/6328.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/VerificationMessageProcessor.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/ThreadSummaryHelper.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/EventMapper.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/LoadRoomMembersTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/threads/FetchThreadTimelineTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/GetEventTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TokenChunkEventPersistor.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/room/RoomSyncHandler.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/room/ThreadsAwarenessHandler.kt
  vector/src/main/java/im/vector/app/core/ui/list/ButtonPositiveDestructiveButtonBarItem.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/VerificationAction.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/VerificationBottomSheetViewModel.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/choose/VerificationChooseMethodController.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/choose/VerificationChooseMethodFragment.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/choose/VerificationChooseMethodViewModel.kt
  vector/src/main/res/layout/item_positive_destrutive_buttons.xml
Labels: A-E2EE-SAS-Verification, Z-NextRelease

#6101 Native lookup fixes
  changelog.d/6101.bugfix
  vector/src/main/java/im/vector/app/features/call/dialpad/DialPadLookup.kt
Labels: Z-Community-PR

#6350 Promote live location labs flag [PSF-959]
  changelog.d/6350.feature
  vector/src/main/java/im/vector/app/features/location/LocationSharingFragment.kt
  vector/src/main/java/im/vector/app/features/location/live/LiveLocationLabsFlagPromotionBottomSheet.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/res/layout/bottom_sheet_live_location_labs_flag_promotion.xml
  vector/src/main/res/values/strings.xml
Labels: A-Location

#6288 Use stable endpoint for alias management
  changelog.d/6288.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/network/ApiPath.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAPI.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/alias/GetRoomLocalAliasesTask.kt
Labels: Z-Community-PR
