Repository element-hq/element-android, pull requests merged in 2022-05, with the labels that each got.

#5696 track room open and room join analytics events
  vector/src/main/java/im/vector/app/features/analytics/extensions/JoinedRoomExt.kt
  vector/src/main/java/im/vector/app/features/analytics/extensions/ViewRoomExt.kt
  vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomActivity.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/IncomingVerificationRequestHandler.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailActivity.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/search/SearchFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt
  vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheet.kt
  vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetState.kt
  vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt
  vector/src/main/java/im/vector/app/features/matrixto/OriginOfMatrixTo.kt
  vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt
  vector/src/main/java/im/vector/app/features/navigation/Navigator.kt
  vector/src/main/java/im/vector/app/features/notifications/NotificationBroadcastReceiver.kt
  vector/src/main/java/im/vector/app/features/permalink/PermalinkHandler.kt
  vector/src/main/java/im/vector/app/features/roomdirectory/PublicRoomsFragment.kt
  vector/src/main/java/im/vector/app/features/roomdirectory/RoomDirectoryActivity.kt
  vector/src/main/java/im/vector/app/features/roomdirectory/RoomDirectoryViewModel.kt
  vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomFragment.kt
  vector/src/main/java/im/vector/app/features/roomdirectory/roompreview/RoomPreviewNoPreviewFragment.kt
  vector/src/main/java/im/vector/app/features/roomdirectory/roompreview/RoomPreviewViewModel.kt
  vector/src/main/java/im/vector/app/features/share/IncomingShareFragment.kt
  vector/src/main/java/im/vector/app/features/spaces/SpaceExploreActivity.kt
  vector/src/main/java/im/vector/app/features/spaces/explore/SpaceDirectoryViewModel.kt
  vector/src/main/java/im/vector/app/features/spaces/people/SpacePeopleActivity.kt
  vector/src/main/java/im/vector/app/features/usercode/UserCodeActivity.kt
Labels: Z-NextRelease

#5912 [SDK] Add missing return type in RoomApi.sendStateEvent()
  changelog.d/5855.sdk
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/state/StateService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAPI.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/state/DefaultStateService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/state/SendStateTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/widgets/CreateWidgetTask.kt
Labels: T-Enhancement, matrix-sdk

#5924 Space list crash fix
  vector/src/main/java/im/vector/app/features/spaces/SpaceSummaryController.kt
Labels: Z-NextRelease

#5869 [Live location sharing] Improve aggregation process of events
  changelog.d/5862.wip
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/EventAnnotationsSummary.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/livelocation/LiveLocationShareAggregatedSummary.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageBeaconInfoContent.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageBeaconLocationDataContent.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageLocationContent.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageType.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/EventAnnotationsSummaryMapper.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/LiveLocationShareAggregatedSummaryMapper.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo027.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/EventAnnotationsSummaryEntity.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/SessionRealmModule.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/livelocation/LiveLocationShareAggregatedSummaryEntity.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/LiveLocationShareAggregatedSummaryEntityQuery.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/EventRelationsAggregationProcessor.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/livelocation/DefaultLiveLocationAggregationProcessor.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/livelocation/LiveLocationAggregationProcessor.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/state/DefaultStateService.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/LiveLocationMessageItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/style/TimelineMessageLayoutFactory.kt
  vector/src/main/java/im/vector/app/features/location/LocationSharingService.kt
Labels: A-Location

#5926 Crash - Konfetti API 21/22 crash
  changelog.d/5925.bugfix
  vector/src/main/java/im/vector/app/core/ui/views/CompatKonfetti.kt
  vector/src/main/res/layout/fragment_ftue_account_created.xml
  vector/src/main/res/layout/fragment_ftue_personalization_complete.xml
  vector/src/main/res/layout/fragment_timeline.xml
Labels: Z-Crash, Z-NextRelease

#5909 Fixes crash when accepting VOIP calls
  changelog.d/5421.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/EventInsertLiveObserver.kt
Labels: Z-Crash, PR-Small

#5928 Fixing sign in via Other needing registration to be enabled
  changelog.d/5874.bugfix
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
Labels: Z-FTUE, Z-NextRelease, PR-Small

#5950 Fixing crash on launch - Missing migration
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo028.kt
Labels: Z-Crash

#5948 Add diag request for Synapse
  tools/hs_diag.py
Labels: PR-Small

#5945 Add small step at the beginning of the release flow
  .github/ISSUE_TEMPLATE/release.yml
Labels: PR-Small

#5965 Handling SSL/TLS errors during WellKnown lookup
  changelog.d/5965.sdk
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/DefaultAuthenticationService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/wellknown/GetWellknownTask.kt
Labels: matrix-sdk, PR-Small

#5831 Updated copy and moved override in profile screen
  changelog.d/5825.bugfix
  vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileController.kt
  vector/src/main/res/values/strings.xml
Labels: Z-Community-PR

#5936 Added themed icon for Android 13
  changelog.d/5936.feature
  vector/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  vector/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: Z-Community-PR

#6013 FTUE - Temporarily hide EMS section
  vector/src/main/res/layout/fragment_ftue_server_selection_combined.xml
Labels: Z-FTUE, PR-Small

#6047 add presence indicator busy and away
  changelog.d/6047.feature
  library/ui-styles/src/main/res/values/colors.xml
  library/ui-styles/src/main/res/values/palette.xml
  library/ui-styles/src/main/res/values/theme_dark.xml
  library/ui-styles/src/main/res/values/theme_light.xml
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/presence/model/PresenceEnum.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncPresence.kt
  vector/src/main/java/im/vector/app/core/ui/views/PresenceStateImageView.kt
  vector/src/main/res/drawable/ic_presence_away.xml
  vector/src/main/res/drawable/ic_presence_busy.xml
  vector/src/main/res/values/strings.xml
Labels: Z-Community-PR

#6079 Fix translation
  vector/src/main/res/values-ar/strings.xml
  vector/src/main/res/values-bg/strings.xml
  vector/src/main/res/values-bn-rBD/strings.xml
  vector/src/main/res/values-bn-rIN/strings.xml
  vector/src/main/res/values-ca/strings.xml
  vector/src/main/res/values-cs/strings.xml
  vector/src/main/res/values-de/strings.xml
  vector/src/main/res/values-eo/strings.xml
  vector/src/main/res/values-es/strings.xml
  vector/src/main/res/values-et/strings.xml
  vector/src/main/res/values-eu/strings.xml
  vector/src/main/res/values-fa/strings.xml
  vector/src/main/res/values-fi/strings.xml
  vector/src/main/res/values-fr-rCA/strings.xml
  vector/src/main/res/values-fr/strings.xml
  vector/src/main/res/values-gl/strings.xml
  vector/src/main/res/values-hr/strings.xml
  vector/src/main/res/values-hu/strings.xml
  vector/src/main/res/values-in/strings.xml
  vector/src/main/res/values-is/strings.xml
  vector/src/main/res/values-it/strings.xml
  vector/src/main/res/values-iw/strings.xml
  vector/src/main/res/values-ja/strings.xml
  vector/src/main/res/values-kab/strings.xml
  vector/src/main/res/values-ko/strings.xml
  vector/src/main/res/values-lo/strings.xml
  vector/src/main/res/values-lv/strings.xml
  vector/src/main/res/values-ml/strings.xml
  vector/src/main/res/values-nb-rNO/strings.xml
  vector/src/main/res/values-nl/strings.xml
  vector/src/main/res/values-nn/strings.xml
  vector/src/main/res/values-pl/strings.xml
  vector/src/main/res/values-pt-rBR/strings.xml
  vector/src/main/res/values-pt/strings.xml
  vector/src/main/res/values-ru/strings.xml
  vector/src/main/res/values-sk/strings.xml
  vector/src/main/res/values-sq/strings.xml
  vector/src/main/res/values-sv/strings.xml
  vector/src/main/res/values-tr/strings.xml
  vector/src/main/res/values-uk/strings.xml
  vector/src/main/res/values-vi/strings.xml
  vector/src/main/res/values-zh-rCN/strings.xml
  vector/src/main/res/values-zh-rTW/strings.xml
  vector/src/main/res/values/strings.xml
Labels: Z-NextRelease

#5856 Use fixed text size in read receipt counter
  changelog.d/5856.bugfix
  library/ui-styles/src/main/res/values/styles_timeline.xml
  vector/src/main/res/layout/view_read_receipts.xml
Labels: Z-Community-PR

#6164 Ask the user to confirm urls which contain unicode direction overrides
  changelog.d/6163.feature
  vector/src/main/java/im/vector/app/core/extensions/String.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/test/java/im/vector/app/core/extensions/StringExtensionsTest.kt
Labels: Z-NextRelease

#6182 Docs: Fix various formatting and spelling issues in notifications.md
  docs/notifications.md
Labels: Z-Community-PR

#6183 Fix some notifications never getting dismissed
  changelog.d/4862.bugfix
  vector/src/main/java/im/vector/app/features/notifications/NotifiableEventResolver.kt
  vector/src/main/java/im/vector/app/features/notifications/NotifiableMessageEvent.kt
  vector/src/main/java/im/vector/app/features/notifications/NotificationBroadcastReceiver.kt
  vector/src/test/java/im/vector/app/test/fixtures/NotifiableEventFixture.kt
Labels: Z-Community-PR

#6166 [Feature] Add the option to autoplay animated images
  changelog.d/6166.feature
  vector/src/main/java/im/vector/app/core/resources/UserPreferencesProvider.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/MessageInformationDataFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/MessageItemAttributesFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageItem.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageImageVideoItem.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageInformationData.kt
  vector/src/main/java/im/vector/app/features/media/ImageContentRenderer.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/res/values/strings.xml
  vector/src/main/res/xml/vector_settings_preferences.xml
Labels: Z-Community-PR

#6132 Fixed grammar in 2 English strings
  changelog.d/6132.misc
  vector/src/main/res/values/strings.xml
Labels: Z-Community-PR

#6202 Remove unused strings.
  vector/src/main/res/values-ca/strings.xml
  vector/src/main/res/values-cs/strings.xml
  vector/src/main/res/values-de/strings.xml
  vector/src/main/res/values-eo/strings.xml
  vector/src/main/res/values-es/strings.xml
  vector/src/main/res/values-et/strings.xml
  vector/src/main/res/values-fa/strings.xml
  vector/src/main/res/values-fi/strings.xml
  vector/src/main/res/values-fr/strings.xml
  vector/src/main/res/values-hu/strings.xml
  vector/src/main/res/values-in/strings.xml
  vector/src/main/res/values-is/strings.xml
  vector/src/main/res/values-it/strings.xml
  vector/src/main/res/values-iw/strings.xml
  vector/src/main/res/values-ja/strings.xml
  vector/src/main/res/values-lo/strings.xml
  vector/src/main/res/values-nl/strings.xml
  vector/src/main/res/values-pl/strings.xml
  vector/src/main/res/values-pt-rBR/strings.xml
  vector/src/main/res/values-ru/strings.xml
  vector/src/main/res/values-sk/strings.xml
  vector/src/main/res/values-sq/strings.xml
  vector/src/main/res/values-sv/strings.xml
  vector/src/main/res/values-uk/strings.xml
  vector/src/main/res/values-vi/strings.xml
  vector/src/main/res/values-zh-rCN/strings.xml
  vector/src/main/res/values-zh-rTW/strings.xml
  vector/src/main/res/values/strings.xml
Labels: Z-NextRelease

#5827 do not switch away from home space on notification
  changelog.d/5827.bugfix
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
Labels: Z-Community-PR, Z-NextRelease

#6205 Use fatalError instead of NPE
  vector/src/main/java/im/vector/app/features/widgets/webview/WebviewPermissionUtils.kt
  vector/src/test/java/im/vector/app/features/widgets/WebviewPermissionUtilsTest.kt
Labels: Z-NextRelease

#5528 Fix missing/swapped/duplicated messages due to wrong TimelineChunk modifications or insertions
  changelog.d/5528.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt
Labels: Z-Community-PR

#5970 Make read receipt avatar list more compact
  changelog.d/5970.feature
  vector/src/main/java/im/vector/app/core/ui/views/ReadReceiptsView.kt
  vector/src/main/res/layout/view_read_receipts.xml
  vector/src/main/res/values/strings.xml
Labels: X-Needs-Design, Z-Community-PR
