Repository element-hq/element-android, pull requests merged in 2022-07, with the labels that each got.

#6450 Gallery picker can pick external images (not just videos)
  changelog.d/6450.bugfix
  library/multipicker/src/main/java/im/vector/lib/multipicker/MediaPicker.kt
Labels: Z-Community-PR

#6425 [Poll] - Add a description under undisclosed poll when not ended (PSB-134)
  changelog.d/6423.misc
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/PollItemViewStateFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/PollItem.kt
  vector/src/main/java/im/vector/app/features/poll/PollViewState.kt
  vector/src/main/res/layout/item_timeline_event_poll.xml
  vector/src/main/res/values/strings.xml
  vector/src/test/java/im/vector/app/features/home/room/detail/timeline/factory/PollItemViewStateFactoryTest.kt
Labels: PR-Small

#6431 [Poll] - Wrong votes in closed poll after removing 2 previous polls (PSG-590)
  changelog.d/6430.bugfix
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/PollOptionView.kt
Labels: PR-Small

#6157 [FTUE] MSISDN / Phone number confirmation
  vector/src/main/java/im/vector/app/core/di/FragmentModule.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthPhoneConfirmationFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt
  vector/src/main/res/layout/fragment_ftue_phone_confirmation.xml
  vector/src/main/res/values/donottranslate.xml
Labels: Z-FTUE

#6447 Fix HTML entities being displayed in messages
  changelog.d/6442.bugfix
  vector/src/main/java/im/vector/app/features/html/EventHtmlRenderer.kt
Labels: Z-Community-PR

#6456 Fix copy paste issue
  vector/src/debug/java/im/vector/app/features/debug/features/DebugVectorFeatures.kt
Labels: PR-Small

#6467 Crash - Sharing text
  changelog.d/6451.bugfix
  vector/src/main/java/im/vector/app/features/attachments/AttachmentsHelper.kt
  vector/src/main/java/im/vector/app/features/attachments/ShareIntentHandler.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/main/java/im/vector/app/features/share/IncomingShareFragment.kt
  vector/src/main/res/values/strings.xml
Labels: Z-Crash, Z-NextRelease

#6469 Fix ConcurrentModificationException on BackgroundDetectionObserver
  changelog.d/6469.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/BackgroundDetectionObserver.kt
Labels: Z-NextRelease

#6474 Fix crashes when opening Thread (#6463)
  changelog.d/6463.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt
Labels: Z-NextRelease

#6462 Timeline: fix validation of timeline event changes
  changelog.d/6461.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt
Labels: Z-NextRelease

#6454 FTUE - Homeserver edits not updating the selected server UI
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
  vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
Labels: Z-FTUE, PR-Small

#6489 Add dependency to opusencoder and remove module from this project
  dependencies.gradle
  dependencies_groups.gradle
  library/opusencoder/.gitignore
  library/opusencoder/build.gradle
  library/opusencoder/src/main/AndroidManifest.xml
  library/opusencoder/src/main/cpp/CMakeLists.txt
  library/opusencoder/src/main/cpp/codec/CodecOggOpus.cpp
  library/opusencoder/src/main/cpp/codec/CodecOggOpus.h
  library/opusencoder/src/main/cpp/opus/include/opus.h
  library/opusencoder/src/main/cpp/opus/include/opus_custom.h
  library/opusencoder/src/main/cpp/opus/include/opus_defines.h
  library/opusencoder/src/main/cpp/opus/include/opus_multistream.h
  library/opusencoder/src/main/cpp/opus/include/opus_projection.h
  library/opusencoder/src/main/cpp/opus/include/opus_types.h
  library/opusencoder/src/main/cpp/opus/include/opusenc.h
  library/opusencoder/src/main/cpp/opus/libs/arm64-v8a/libopus.so
  library/opusencoder/src/main/cpp/opus/libs/arm64-v8a/libopusenc.so
  library/opusencoder/src/main/cpp/opus/libs/armeabi-v7a/libopus.so
  library/opusencoder/src/main/cpp/opus/libs/armeabi-v7a/libopusenc.so
  library/opusencoder/src/main/cpp/opus/libs/x86/libopus.so
  library/opusencoder/src/main/cpp/opus/libs/x86/libopusenc.so
  library/opusencoder/src/main/cpp/opus/libs/x86_64/libopus.so
  library/opusencoder/src/main/cpp/opus/libs/x86_64/libopusenc.so
  library/opusencoder/src/main/cpp/opuscodec.cpp
  library/opusencoder/src/main/cpp/utils/Logger.h
  library/opusencoder/src/main/java/im/vector/opusencoder/OggOpusEncoder.kt
  library/opusencoder/src/main/java/im/vector/opusencoder/configuration/SampleRate.kt
  settings.gradle
  vector/build.gradle
  vector/src/androidTest/java/im/vector/app/features/voice/VoiceRecorderProviderTests.kt
  vector/src/debug/java/im/vector/app/features/debug/features/DebugFeaturesStateFactory.kt
  vector/src/debug/java/im/vector/app/features/debug/features/DebugVectorFeatures.kt
  vector/src/main/java/im/vector/app/features/VectorFeatures.kt
  vector/src/main/java/im/vector/app/features/voice/VoiceRecorderL.kt
  vector/src/main/java/im/vector/app/features/voice/VoiceRecorderProvider.kt
Labels: Z-NextRelease

#6511 Fixes inconsistent rooms in home behaviour
  changelog.d/6510.bugfix
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
Labels: A-Spaces

#6471 Adding tests around the share intent handling
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/util/MimeTypes.kt
  vector/src/main/java/im/vector/app/features/attachments/MultiPickerIncomingFiles.kt
  vector/src/main/java/im/vector/app/features/attachments/ShareIntentHandler.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/main/java/im/vector/app/features/share/IncomingShareFragment.kt
  vector/src/test/java/im/vector/app/features/attachments/ShareIntentHandlerTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeFunction1.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeIntent.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeMultiPickerIncomingFiles.kt
  vector/src/test/java/im/vector/app/test/fixtures/ContentAttachmentDataFixture.kt
Labels: Z-Tests

#6512 UI test stabilization
  vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt
  vector/src/androidTest/java/im/vector/app/ui/robot/CreateNewRoomRobot.kt
  vector/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt
  vector/src/androidTest/java/im/vector/app/ui/robot/MessageMenuRobot.kt
  vector/src/androidTest/java/im/vector/app/ui/robot/RoomDetailRobot.kt
  vector/src/androidTest/java/im/vector/app/ui/robot/space/SpaceCreateRobot.kt
  vector/src/androidTest/java/im/vector/app/ui/robot/space/SpaceMenuRobot.kt
  vector/src/androidTest/java/im/vector/app/ui/robot/space/SpaceRobot.kt
Labels: Z-Tests

#6545 FTUE - Combined register copy review
  changelog.d/6546.feature
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/MatrixPatterns.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/api/MatrixPatternsTest.kt
  vector/src/main/java/im/vector/app/core/extensions/BasicExtensions.kt
  vector/src/main/java/im/vector/app/core/extensions/TextInputLayout.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingAction.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewState.kt
  vector/src/main/java/im/vector/app/features/onboarding/StartAuthenticationFlowUseCase.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedLoginFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedRegisterFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueExtensions.kt
  vector/src/main/res/layout/fragment_ftue_combined_register.xml
  vector/src/main/res/values/donottranslate.xml
  vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
  vector/src/test/java/im/vector/app/features/onboarding/StartAuthenticationFlowUseCaseTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeRegistrationWizard.kt
Labels: Z-FTUE

#6569 FTUE - Copy review
  changelog.d/6547.feature
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthAccountCreatedFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthEmailEntryFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthPhoneEntryFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthResetPasswordBreakerFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthResetPasswordEmailEntryFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/terms/FtueAuthTermsFragment.kt
  vector/src/main/res/layout/fragment_ftue_combined_login.xml
  vector/src/main/res/layout/fragment_ftue_display_name.xml
  vector/src/main/res/layout/fragment_ftue_email_input.xml
  vector/src/main/res/layout/fragment_ftue_login_captcha.xml
  vector/src/main/res/layout/fragment_ftue_login_terms.xml
  vector/src/main/res/layout/fragment_ftue_phone_input.xml
  vector/src/main/res/layout/fragment_ftue_reset_password_email_input.xml
  vector/src/main/res/layout/fragment_ftue_server_selection_combined.xml
  vector/src/main/res/values/donottranslate.xml
  vector/src/main/res/values/strings.xml
  vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
Labels: Z-FTUE

#6200 Fixes room not being in space after upgrade
  changelog.d/6200.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/VersioningState.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/upgrade/UpgradeRoomViewModelTask.kt
  vector/src/main/java/im/vector/app/features/spaces/explore/SpaceDirectoryController.kt
  vector/src/test/java/org/matrix/android/sdk/api/session/room/model/VersioningStateTest.kt
Labels: PR-Small

#6624 Fix crash observed on nightly build
  vector/src/main/java/im/vector/app/features/popup/PopupAlertManager.kt
Labels: Z-NextRelease

#6341 Fixed issues with reporting sync state events from different threads
  changelog.d/6341.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/sync/SyncService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/DefaultSyncService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncRequestStateTracker.kt
  vector/src/main/java/im/vector/app/AppStateHandler.kt
  vector/src/main/java/im/vector/app/AutoRageShaker.kt
  vector/src/main/java/im/vector/app/features/analytics/accountdata/AnalyticsAccountDataViewModel.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
  vector/src/main/java/im/vector/app/features/home/HomeDetailViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
Labels: Z-Community-PR

#6626 [Location sharing] - OnTap on the top live status bar, display the expanded map view (PSG-614)
  changelog.d/6625.misc
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
Labels: PR-Small

#6643 Feature/bma/fix firebase popup
  vector/src/fdroid/java/im/vector/app/nightly/NightlyProxy.kt
  vector/src/gplay/java/im/vector/app/nightly/NightlyProxy.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
Labels: Z-NextRelease

#6649 FTUE - Test session feedback
  changelog.d/6620.feature
  changelog.d/6621.feature
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/Extensions.kt
  vector/src/main/java/im/vector/app/core/error/ErrorFormatter.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedRegisterFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedServerSelectionFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthResetPasswordEntryFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthWaitForEmailFragment.kt
  vector/src/main/res/drawable/ic_robot.xml
  vector/src/main/res/layout/fragment_ftue_combined_login.xml
  vector/src/main/res/layout/fragment_ftue_login_captcha.xml
  vector/src/main/res/layout/fragment_ftue_server_selection_combined.xml
  vector/src/main/res/layout/fragment_ftue_wait_for_email_verification.xml
  vector/src/main/res/values/strings.xml
Labels: Z-FTUE

#6641 FTUE - Allow editing email during email verification
  changelog.d/6622.feature
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewEvents.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewState.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/AbstractFtueAuthFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthEmailEntryFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthWaitForEmailFragment.kt
  vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeRegistrationWizard.kt
Labels: Z-FTUE, Z-NextRelease

#6656 Revert #6404
  changelog.d/5546.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimelineService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt
Labels: Z-NextRelease

#6664 Cancel infinite animations in TypingMessageDotsView
  changelog.d/6663.bugfix
  vector/src/main/java/im/vector/app/core/ui/views/TypingMessageDotsView.kt
Labels: Z-NextRelease, PR-Small

#6666 `Home` always showing all rooms
  changelog.d/6665.bugfix
  changelog.d/6666.sdk
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/query/SpaceFilter.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomSummaryQueryParams.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryDataSource.kt
  vector/src/main/java/im/vector/app/features/home/HomeDetailViewModel.kt
  vector/src/main/java/im/vector/app/features/home/UnreadMessagesSharedViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/list/RoomListSectionBuilder.kt
  vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt
  vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt
Labels: Z-NextRelease

#6677 Shortcuts must first start MainActivity to ensure the session is restored.
  vector/src/main/java/im/vector/app/features/MainActivity.kt
  vector/src/main/java/im/vector/app/features/home/ShortcutCreator.kt
  vector/src/main/java/im/vector/app/features/home/ShortcutsHandler.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailActivity.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
Labels: Z-NextRelease
