Repository element-hq/element-android, pull requests merged in 2022-02, with the labels that each got.

#5124 Fix timber crash
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/megolm/MXOutboundSessionInfo.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/ThumbnailExtractor.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt
  vector/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt
Labels: Z-NextRelease

#5135 Fixing ignored font weights
  changelog.d/3907.bugfix
  library/ui-styles/src/main/res/values/theme_dark.xml
  library/ui-styles/src/main/res/values/theme_light.xml
Labels: X-Needs-Design

#5106 Enabling FTUE Use Case
  vector/src/androidTest/java/im/vector/app/ui/robot/OnboardingRobot.kt
  vector/src/main/java/im/vector/app/features/VectorFeatures.kt
  vector/src/main/res/layout/fragment_ftue_auth_use_case.xml
  vector/src/main/res/values/donottranslate.xml
  vector/src/main/res/values/strings.xml
Labels: X-Needs-Design, Z-FTUE, X-Needs-Product

#5121 Update workflow for FTUE issues on FTUE board
  .github/workflows/triage-labelled.yml
  changelog.d/5120.misc
  changelog.d/5148.misc
Labels: A-Developer-Experience, T-Task

#5174 Fix WTF automation
  .github/workflows/triage-labelled.yml
  changelog.d/5173.misc
Labels: A-Developer-Experience, T-Task

#5189 #4640 : The notification badge jumps around
  changelog.d/4640.bugfix
  library/ui-styles/src/main/res/values/colors.xml
  vector/src/main/res/layout/item_room.xml
Labels: Z-WTF

#5228 Adding UI test docs section for contributing to the sanity tests
  docs/ui-tests.md
Labels: A-Documentation

#5239 Fixing missing identify properties
  changelog.d/5234.bugfix
  vector/src/main/java/im/vector/app/core/di/NamedGlobalScope.kt
  vector/src/main/java/im/vector/app/core/di/SingletonModule.kt
  vector/src/main/java/im/vector/app/features/analytics/impl/DefaultVectorAnalytics.kt
  vector/src/main/java/im/vector/app/features/analytics/impl/LateInitUserPropertiesFactory.kt
  vector/src/main/java/im/vector/app/features/analytics/impl/PostHogFactory.kt
  vector/src/test/java/im/vector/app/features/analytics/impl/DefaultVectorAnalyticsTest.kt
  vector/src/test/java/im/vector/app/features/analytics/impl/LateInitUserPropertiesFactoryTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeActiveSessionDataSource.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeAnalyticsStore.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeLateInitUserPropertiesFactory.kt
  vector/src/test/java/im/vector/app/test/fakes/FakePostHog.kt
  vector/src/test/java/im/vector/app/test/fakes/FakePostHogFactory.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeSession.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeVectorStore.kt
  vector/src/test/java/im/vector/app/test/fixtures/AnalyticsConfigFixture.kt
  vector/src/test/java/im/vector/app/test/fixtures/UserPropertiesFixture.kt
  vector/src/test/java/im/vector/app/test/fixtures/VectorAnalyticsFixture.kt
Labels: Z-FTUE, Z-Tracking

#5253 #4643: Home screen: replacing the search icon by a filter icon in the menu
  changelog.d/4643.misc
  vector/src/main/res/menu/home.xml
Labels: Z-WTF

#5249 #2782: Collapse server ACLs update events
  changelog.d/2782.misc
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MergedHeaderItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineDisplayableEvents.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MergedSimilarEventsItem.kt
  vector/src/main/res/values/strings.xml
Labels: Z-WTF

#5104 Make Space creation screens more consistent
  changelog.d/5104.misc
  vector/src/main/res/layout/fragment_space_create_choose_private_model.xml
  vector/src/main/res/layout/fragment_space_create_choose_type.xml
  vector/src/main/res/values/strings.xml
Labels: X-Needs-Design, Z-Community-PR

#5276 Reducing bitmap memory footprint
  changelog.d/5276.misc
  vector/src/main/java/im/vector/app/features/home/AdaptiveIconTransformation.kt
  vector/src/main/java/im/vector/app/features/home/AvatarRenderer.kt
  vector/src/main/java/im/vector/app/features/home/ShortcutCreator.kt
  vector/src/main/java/im/vector/app/features/notifications/BitmapLoader.kt
  vector/src/main/java/im/vector/app/features/notifications/IconLoader.kt
  vector/src/main/java/im/vector/app/features/notifications/NotificationBitmapLoader.kt
  vector/src/main/java/im/vector/app/features/notifications/RoomGroupMessageCreator.kt
Labels: Z-NextRelease

#5296 Fixing crash adding room by QR code
  changelog.d/5295.bugfix
  vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomActivity.kt
  vector/src/main/java/im/vector/app/features/qrcode/QrCodeScannerFragment.kt
Labels: Z-Crash, Z-NextRelease

#5297 Improve usage of realm
  changelog.d/5297.misc
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/ReadReceipt.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/AsyncTransaction.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/ReadReceiptsSummaryMapper.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/TimelineEventMapper.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateRoomTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/joining/JoinRoomTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/ReadReceiptsItemFactory.kt
Labels: Z-NextRelease

#5258 #5218: Fix crash at registration when redirecting to Web View
  changelog.d/5218.bugfix
  vector/src/main/java/im/vector/app/features/login/LoginWebFragment.kt
  vector/src/main/java/im/vector/app/features/login2/LoginWebFragment2.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingAction.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthWebFragment.kt
  vector/src/main/java/im/vector/app/features/signout/soft/SoftLogoutViewModel.kt
Labels: Z-Crash, Z-NextRelease

#5158 FTUE - Account created screen
  changelog.d/5158.wip
  vector/src/debug/java/im/vector/app/features/debug/features/DebugFeaturesStateFactory.kt
  vector/src/debug/java/im/vector/app/features/debug/features/DebugVectorFeatures.kt
  vector/src/main/java/im/vector/app/core/di/FragmentModule.kt
  vector/src/main/java/im/vector/app/features/VectorFeatures.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewEvents.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewState.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthAccountCreatedFragment.kt
  vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt
  vector/src/main/res/layout/fragment_ftue_account_created.xml
  vector/src/main/res/values/donottranslate.xml
Labels: Z-FTUE

#5349 #5005: Add save media icon in gallery
  changelog.d/5005.feature
  library/attachment-viewer/src/main/java/im/vector/lib/attachmentviewer/AttachmentViewerActivity.kt
  vector/src/main/java/im/vector/app/core/di/MavericksViewModelModule.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
  vector/src/main/java/im/vector/app/features/media/AttachmentInteractionListener.kt
  vector/src/main/java/im/vector/app/features/media/AttachmentOverlayView.kt
  vector/src/main/java/im/vector/app/features/media/BaseAttachmentProvider.kt
  vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerAction.kt
  vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerActivity.kt
  vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerViewEvents.kt
  vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerViewModel.kt
  vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt
  vector/src/main/res/layout/merge_image_attachment_overlay.xml
  vector/src/test/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCaseTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeFile.kt
Labels: Z-WTF

#5292 #4319: Fix DM navigation in member profile screen
  changelog.d/4319.bugfix
  vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailPendingAction.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
  vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileAction.kt
  vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileFragment.kt
  vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewEvents.kt
  vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewModel.kt
Labels: Z-WTF
