Repository element-hq/element-android, pull requests merged in 2022-11, with the labels that each got.

#6195 Upgrade Jitsi SDK to 6.2.2
  build.gradle
  changelog.d/6195.misc
  docs/jitsi.md
  tools/jitsi/build_jisti_libs.sh
  vector-app/src/debug/AndroidManifest.xml
  vector-app/src/debug/java/im/vector/app/features/debug/DebugMenuActivity.kt
  vector-app/src/debug/java/im/vector/app/features/debug/jitsi/DebugJitsiActivity.kt
  vector-app/src/debug/res/layout/activity_debug_jitsi.xml
  vector-app/src/debug/res/layout/activity_debug_menu.xml
  vector/build.gradle
  vector/src/main/AndroidManifest.xml
  vector/src/main/java/im/vector/app/features/call/conference/ConferenceEvent.kt
  vector/src/main/java/im/vector/app/features/call/conference/VectorJitsiActivity.kt
  vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt
  vector/src/main/res/drawable-hdpi/ic_notification.png
  vector/src/main/res/drawable-mdpi/ic_notification.png
  vector/src/main/res/drawable-xhdpi/ic_notification.png
  vector/src/main/res/drawable-xxhdpi/ic_notification.png
  vector/src/main/res/drawable-xxxhdpi/ic_notification.png
Labels: Z-NextRelease

#7582 Persist the playback state of voice messages across different screens
  changelog.d/7582.feature
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/AudioMessageHelper.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/AudioMessagePlaybackTracker.kt
Labels: Z-NextRelease, PR-Small

#7605 ANR on session start when sending client info is enabled
  changelog.d/7604.bugfix
  vector/src/main/java/im/vector/app/core/di/ActiveSessionHolder.kt
  vector/src/main/java/im/vector/app/core/session/ConfigureAndStartSessionUseCase.kt
  vector/src/test/java/im/vector/app/core/session/ConfigureAndStartSessionUseCaseTest.kt
Labels: PR-Small

#7488 Add setting to allow disabling direct share
  changelog.d/2725.feature
  library/ui-strings/src/main/res/values/strings.xml
  vector/src/main/java/im/vector/app/features/home/ShortcutCreator.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/res/xml/vector_settings_preferences.xml
Labels: Z-Community-PR

#7656 [Voice Broadcast] Remove chunks from the room attachments
  changelog.d/7656.wip
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineEventVisibilityHelper.kt
  vector/src/main/java/im/vector/app/features/roomprofile/uploads/RoomUploadsViewModel.kt
Labels: Z-NextRelease
