Repository element-hq/element-android, pull requests merged in 2023-01, with the labels that each got.

#7917 View event replay
  vector/src/main/java/im/vector/app/core/utils/SharedEvent.kt
Labels: Z-NextRelease

#7432 Add trim to username input when sign-in
  changelog.d/7111.misc
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/login/DefaultLoginWizard.kt
  vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt
Labels: Z-Community-PR

#7898 Fix unexpected live voice broadcast in the room list
  changelog.d/7832.bugfix
  vector/src/main/java/im/vector/app/features/home/room/list/RoomSummaryItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/list/usecase/GetLatestPreviewableEventUseCase.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/usecase/GetRoomLiveVoiceBroadcastsUseCase.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/usecase/GetVoiceBroadcastStateEventLiveUseCase.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/usecase/GetVoiceBroadcastStateEventUseCase.kt
  vector/src/test/java/im/vector/app/features/home/room/list/usecase/GetLatestPreviewableEventUseCaseTest.kt
  vector/src/test/java/im/vector/app/features/voicebroadcast/usecase/GetVoiceBroadcastStateEventUseCaseTest.kt
Labels: A-Voice Broadcast

#7962 Fix oom crashes.
  changelog.d/7962.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/SendingEventsDataSource.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/decorator/UiEchoDecorator.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/SyncResponsePostTreatmentAggregatorHandler.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
Labels: Z-NextRelease

#7976 Support reactions on Voice Broadcast
  changelog.d/7807.misc
  vector/src/main/java/im/vector/app/core/extensions/TimelineEvent.kt
Labels: Z-NextRelease, A-Voice Broadcast

#7974 Send voice message should not be allowed during a voice broadcast recording
  changelog.d/7895.bugfix
  library/ui-strings/src/main/res/values/strings.xml
  vector/src/main/java/im/vector/app/core/error/ErrorFormatter.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/voice/VoiceRecorderFragment.kt
  vector/src/main/java/im/vector/app/features/voice/VoiceFailure.kt
Labels: Z-NextRelease, A-Voice-Messages, A-Voice Broadcast

#7973 Pause voice broadcast listening on new VB recording
  changelog.d/7830.misc
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
Labels: Z-NextRelease, A-Voice Broadcast

#7963 Voice Broadcast - Fix playback scrubbing not working if playback is stopped
  changelog.d/7961.bugfix
  vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt
Labels: Z-NextRelease, A-Voice Broadcast

#7979 Voice Broadcast - Rework internal media players coordination
  changelog.d/7979.misc
  vector/src/main/java/im/vector/app/core/error/ErrorFormatter.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastFailure.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt
Labels: Z-NextRelease, A-Voice Broadcast

#7985 Slow down sentry
  changelog.d/7960.misc
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/extensions/MetricsExtensions.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/metrics/SyncDurationMetricPlugin.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponseHandler.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncTask.kt
  vector/src/main/java/im/vector/app/features/analytics/metrics/sentry/SentrySyncDurationMetrics.kt
Labels: Z-NextRelease

#7993 Pause voice broadcast if there is no network
  changelog.d/7890.feature
  library/ui-strings/src/main/res/values/strings.xml
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageVoiceBroadcastRecordingItem.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/recording/VoiceBroadcastRecorder.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/recording/VoiceBroadcastRecorderQ.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/recording/usecase/PauseVoiceBroadcastUseCase.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/recording/usecase/StartVoiceBroadcastUseCase.kt
  vector/src/main/res/layout/item_timeline_event_voice_broadcast_listening_stub.xml
  vector/src/main/res/layout/item_timeline_event_voice_broadcast_recording_stub.xml
  vector/src/test/java/im/vector/app/features/voicebroadcast/usecase/StartVoiceBroadcastUseCaseTest.kt
Labels: Z-NextRelease

#7988 Implement MSC3912 to delete server side all the data of a deleted voice broadcast
  changelog.d/7967.feature
  changelog.d/7988.sdk
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/homeserver/HomeServerCapabilities.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/send/SendService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/version/Versions.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/tasks/RedactEventTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/HomeServerCapabilitiesMapper.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo049.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/HomeServerCapabilitiesEntity.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/homeserver/GetHomeServerCapabilitiesTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAPI.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/DefaultSendService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/RedactEventWorker.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/model/EventRedactBody.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/EventSenderProcessor.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/EventSenderProcessorCoroutine.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/QueueMemento.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/QueuedTaskFactory.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/RedactQueuedTask.kt
  vector/src/main/java/im/vector/app/core/extensions/TimelineEvent.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/model/VoiceBroadcastEvent.kt
Labels: Z-NextRelease

#8006 [Push rules] Call /actions api before /enabled api (PSG-1099)
  changelog.d/8005.sdk
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/pushers/UpdatePushRuleActionsTask.kt
Labels: matrix-sdk, PR-Small

#8019 Start sync
  library/ui-strings/src/main/res/values/donottranslate.xml
  matrix-sdk-android-flow/src/main/java/org/matrix/android/sdk/flow/FlowSession.kt
  vector/src/main/java/im/vector/app/core/session/EnsureSessionSyncingUseCase.kt
  vector/src/main/java/im/vector/app/features/command/Command.kt
  vector/src/main/java/im/vector/app/features/command/CommandParser.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
  vector/src/main/java/im/vector/app/features/home/HomeDetailViewState.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewState.kt
  vector/src/main/java/im/vector/app/features/sync/widget/SyncStateView.kt
  vector/src/main/res/layout/fragment_timeline.xml
  vector/src/test/java/im/vector/app/features/command/CommandParserTest.kt
Labels: Z-NextRelease

#8031 Do not send any request to Posthog if no consent is provided.
  changelog.d/8031.bugfix
  vector/src/main/java/im/vector/app/features/analytics/impl/DefaultVectorAnalytics.kt
  vector/src/test/java/im/vector/app/features/analytics/impl/DefaultVectorAnalyticsTest.kt
Labels: Z-NextRelease

#8012 [Voice Broadcast] Use internal playback timer to compute the playback position
  changelog.d/8012.bugfix
  library/attachment-viewer/src/main/java/im/vector/lib/attachmentviewer/VideoViewHolder.kt
  library/core-utils/src/main/java/im/vector/lib/core/utils/timer/Clock.kt
  library/core-utils/src/main/java/im/vector/lib/core/utils/timer/CountUpTimer.kt
  tools/check/forbidden_strings_in_code.txt
  vector/src/main/java/im/vector/app/features/call/webrtc/WebRtcCall.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/AudioMessageHelper.kt
  vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationUserItem.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlaylist.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/model/MessageVoiceBroadcastInfoContent.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/recording/VoiceBroadcastRecorderQ.kt
  vector/src/main/res/layout/item_timeline_event_voice_broadcast_listening_stub.xml
Labels: Z-NextRelease

#8042 [Voice Broadcast] Move the live broadcast computation in the room list behind the lab flag
  changelog.d/8042.misc
  vector/src/main/java/im/vector/app/features/home/room/list/usecase/GetLatestPreviewableEventUseCase.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/listening/usecase/GetLiveVoiceBroadcastChunksUseCase.kt
  vector/src/test/java/im/vector/app/features/home/room/list/usecase/GetLatestPreviewableEventUseCaseTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeVectorPreferences.kt
Labels: Z-NextRelease
