Repository element-hq/element-android, pull requests merged in 2023-02, with the labels that each got.

#8058 Improve CountUpTimer ticks precision
  changelog.d/8058.misc
  library/attachment-viewer/src/main/java/im/vector/lib/attachmentviewer/VideoViewHolder.kt
  library/core-utils/build.gradle
  library/core-utils/src/main/java/im/vector/lib/core/utils/timer/CountUpTimer.kt
  library/core-utils/src/test/java/im/vector/lib/core/utils/test/fakes/FakeClock.kt
  library/core-utils/src/test/java/im/vector/lib/core/utils/timer/CountUpTimerTest.kt
  tools/check/forbidden_strings_in_code.txt
  vector-app/build.gradle
  vector-app/src/androidTest/java/im/vector/app/EspressoExt.kt
  vector-app/src/androidTest/java/im/vector/app/espresso/tools/ScreenshotFailureRule.kt
  vector-app/src/debug/java/im/vector/app/features/debug/DebugMenuActivity.kt
  vector-app/src/fdroid/java/im/vector/app/fdroid/BackgroundSyncStarter.kt
  vector-app/src/fdroid/java/im/vector/app/fdroid/receiver/AlarmSyncBroadcastReceiver.kt
  vector-app/src/gplay/java/im/vector/app/nightly/FirebaseNightlyProxy.kt
  vector-app/src/main/java/im/vector/app/core/di/SingletonModule.kt
  vector/src/main/java/im/vector/app/core/date/VectorDateFormatter.kt
  vector/src/main/java/im/vector/app/core/di/SingletonEntryPoint.kt
  vector/src/main/java/im/vector/app/core/dialogs/GalleryOrCameraDialogHelper.kt
  vector/src/main/java/im/vector/app/core/dialogs/GalleryOrCameraDialogHelperFactory.kt
  vector/src/main/java/im/vector/app/core/services/VectorSyncAndroidService.kt
  vector/src/main/java/im/vector/app/features/analytics/DecryptionFailureTracker.kt
  vector/src/main/java/im/vector/app/features/attachments/preview/AttachmentsPreviewFragment.kt
  vector/src/main/java/im/vector/app/features/call/conference/JitsiService.kt
  vector/src/main/java/im/vector/app/features/call/webrtc/ScreenCaptureAndroidService.kt
  vector/src/main/java/im/vector/app/features/crypto/keysbackup/setup/KeysBackupSetupSharedViewModel.kt
  vector/src/main/java/im/vector/app/features/crypto/verification/IncomingVerificationRequestHandler.kt
  vector/src/main/java/im/vector/app/features/home/SetUnverifiedSessionsAlertShownUseCase.kt
  vector/src/main/java/im/vector/app/features/home/ShouldShowUnverifiedSessionsAlertUseCase.kt
  vector/src/main/java/im/vector/app/features/home/UnknownDeviceDetectorSharedViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/ChatEffectManager.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/RoomMessageTouchHelperCallback.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/AudioMessageHelper.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/voice/VoiceMessageRecorderView.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/composer/voice/VoiceRecorderFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/search/SearchResultController.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/edithistory/ViewEditHistoryEpoxyController.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/VerificationRequestItem.kt
  vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationBottomSheetController.kt
  vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationUserItem.kt
  vector/src/main/java/im/vector/app/features/location/live/tracking/LiveLocationNotificationBuilder.kt
  vector/src/main/java/im/vector/app/features/media/domain/usecase/DownloadMediaUseCase.kt
  vector/src/main/java/im/vector/app/features/notifications/NotifiableEventResolver.kt
  vector/src/main/java/im/vector/app/features/notifications/NotificationBroadcastReceiver.kt
  vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt
  vector/src/main/java/im/vector/app/features/popup/PopupAlertManager.kt
  vector/src/main/java/im/vector/app/features/roomprofile/uploads/RoomUploadsFragment.kt
  vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
  vector/src/main/java/im/vector/app/features/settings/devices/v2/list/CheckIfSessionIsInactiveUseCase.kt
  vector/src/main/java/im/vector/app/features/settings/devtools/KeyRequestsFragment.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/recording/VoiceBroadcastRecorderQ.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeClock.kt
Labels: Z-NextRelease

#6457 Implement the current spec for event match conditions
  changelog.d/6457.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/pushrules/EventMatchCondition.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/pushrules/rest/PushCondition.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/pushrules/PushRuleFinder.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/api/session/pushrules/PushRulesConditionTest.kt
  vector/src/main/java/im/vector/app/features/settings/push/PushRuleItem.kt
Labels: Z-Community-PR

#8086 Open general settings performance
  changelog.d/5918.bugfix
  vector/src/main/java/im/vector/app/core/utils/FileUtils.kt
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt
Labels: Z-NextRelease

#8057 Let the user know when we are not able to decrypt the voice broadcast…
  changelog.d/7820.misc
  library/ui-strings/src/main/res/values/strings.xml
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/EventService.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/EventEntityQueries.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/events/DefaultEventService.kt
  vector/src/main/java/im/vector/app/core/error/ErrorFormatter.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/TimelineItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/VoiceBroadcastItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineEventsGroups.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageVoiceBroadcastItem.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageVoiceBroadcastListeningItem.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastFailure.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt
  vector/src/main/java/im/vector/app/features/voicebroadcast/listening/usecase/GetLiveVoiceBroadcastChunksUseCase.kt
Labels: Z-NextRelease

#8115 Replace 'Use Bots' with 'Use bots' for localization experience on Weblate
  changelog.d/8115.misc
  library/ui-strings/src/main/res/values/strings.xml
Labels: Z-Community-PR

#8126 [Poll] Fix votes aggregation process (PSG-1153)
  changelog.d/6121.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/DefaultPollAggregationProcessor.kt
  matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/DefaultPollAggregationProcessorTest.kt
Labels: A-Polls, PR-Small

#8152 Fix always jumps to the bottom of the timeline #8090
  changelog.d/8090.bugfix
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
Labels: Z-NextRelease

#8160 Space setting category doesn't show up
  changelog.d/7989.bugfix
  vector/src/main/java/im/vector/app/features/settings/VectorSettingsPreferencesFragment.kt
Labels: PR-Small
