Repository element-hq/element-android, pull requests merged in 2023-03, with the labels that each got.

#8190 [Poll history] Fixing small issue about font style (PSG-1178)
  changelog.d/8190.bugfix
  vector/src/main/res/layout/fragment_room_polls_list.xml
Labels: PR-Small

#8168 matrix-sdk: Ensure correct room for events loaded by chunks
  changelog.d/8168.bugfix
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/ThreadEventsHelper.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ChunkEntityQueries.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/FetchTokenAndPaginateTask.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt
Labels: Z-Community-PR

#8172 create encrypted DM for user invite by email
  changelog.d/6912.misc
  library/ui-strings/src/main/res/values/strings.xml
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateRoomBodyBuilder.kt
  matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/RoomDisplayNameResolver.kt
  vector/src/main/java/im/vector/app/core/di/MavericksViewModelModule.kt
  vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomActivity.kt
  vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomViewModel.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/EncryptionItemFactory.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MergedRoomCreationItem.kt
  vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/StatusTileTimelineItem.kt
  vector/src/main/java/im/vector/app/features/homeserver/HomeServerCapabilitiesViewModel.kt
  vector/src/main/java/im/vector/app/features/homeserver/HomeServerCapabilitiesViewState.kt
  vector/src/main/java/im/vector/app/features/userdirectory/UserListController.kt
  vector/src/main/java/im/vector/app/features/userdirectory/UserListFragment.kt
  vector/src/main/java/im/vector/app/features/userdirectory/UserListFragmentArgs.kt
  vector/src/main/java/im/vector/app/features/userdirectory/UserListViewModel.kt
  vector/src/main/java/im/vector/app/features/userdirectory/UserListViewState.kt
Labels: Z-NextRelease

#8193 Be able to let the user trust several Fingerprints during login flow.
  vector/src/main/java/im/vector/app/features/login/HomeServerConnectionConfigFactory.kt
  vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
  vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
  vector/src/test/java/im/vector/app/test/fakes/FakeHomeServerConnectionConfigFactory.kt
Labels: X-Regression, Z-NextRelease

#8208 Remove hardcoded color on save button
  changelog.d/8208.bugfix
  vector/src/main/res/drawable/ic_composer_rich_text_save.xml
Labels: Z-Community-PR

#8235 Add RTL support to RemoveJitsiWidgetView
  changelog.d/8210.bugfix
  vector/src/main/java/im/vector/app/features/call/conference/RemoveJitsiWidgetView.kt
Labels: Z-Community-PR
